import { Helmet } from "react-helmet-async";
import { FileClock, GitCompareArrows, Languages } from "lucide-react";
import AIDataServicesLayout from "../../shared/AIDataServicesLayout";
import SEOHead from "../../shared/SEOHead";
import ServiceCTA from "../../shared/ServiceCTA";
import ServiceHero from "../../shared/ServiceHero";
import { preparationFaqs, preparationOffers } from "./DataCleaningPreparationContent";
import { CleaningPillars, CostRelatedWhy, DeliverablesAutomation, DistributionImpact, FormatsSecurityEngagement, IndicEncoding, MissingOutliersStructure, PreparationDefinition, PreparationFAQ, PreparationMotionStyles, PreparationProcess, PreparationTrustStrip, WhenNotToClean } from "./DataCleaningPreparationCoreSections";

const canonical="https://www.eqourse.com/ai-data-services/cleaning-validation/data-cleaning-preparation";
const schema={"@context":"https://schema.org","@graph":[{"@type":"Service","@id":`${canonical}#service`,name:"Data Cleaning & Preparation Services",serviceType:"Data Cleaning and Preparation for AI",url:canonical,description:"Data cleaning and preparation for AI training data including deduplication, encoding repair, Unicode normalisation, noise removal, missing-value analysis, outlier adjudication and structural repair, with reversible change logs and distribution-impact reporting.",provider:{"@type":"Organization",name:"eQOURSE",url:"https://www.eqourse.com/",address:[{"@type":"PostalAddress",addressCountry:"IN"},{"@type":"PostalAddress",addressCountry:"SG"}]},areaServed:"Worldwide",availableLanguage:["en","hi","bn","ta","te","mr","gu","kn","ml","pa","or","as","ur"],isPartOf:{"@type":"Service","@id":"https://www.eqourse.com/ai-data-services/cleaning-validation#service",name:"Data Cleaning & Validation Services",url:"https://www.eqourse.com/ai-data-services/cleaning-validation"},hasOfferCatalog:{"@type":"OfferCatalog",name:"Data Cleaning and Preparation Services",itemListElement:preparationOffers.map(name=>({"@type":"Offer",itemOffered:{"@type":"Service",name}}))}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://www.eqourse.com/"},{"@type":"ListItem",position:2,name:"AI Data Services",item:"https://www.eqourse.com/ai-data-services"},{"@type":"ListItem",position:3,name:"Data Cleaning & Validation",item:"https://www.eqourse.com/ai-data-services/cleaning-validation"},{"@type":"ListItem",position:4,name:"Data Cleaning & Preparation",item:canonical}]},{"@type":"FAQPage",mainEntity:preparationFaqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};

const DataCleaningPreparationPage=()=> <AIDataServicesLayout breadcrumbs={[{label:"AI Data Services",href:"/ai-data-services"},{label:"Data Cleaning & Validation",href:"/ai-data-services/cleaning-validation"},{label:"Data Cleaning & Preparation"}]}>
  <SEOHead title="Data Cleaning & Preparation Services for AI | eQOURSE" description="Deduplication, encoding repair, noise removal and data normalisation for AI—with reversible change logs and before-and-after distribution reporting." canonical={canonical} keywords="data cleaning services, data preparation services for machine learning, data cleansing services, data preprocessing services, data deduplication services, data normalization services" ogImage="https://www.eqourse.com/assets/ai-data/cleaning-validation/data-cleaning-preparation/data-cleaning-preparation-og.webp"/>
  <Helmet><meta name="robots" content="index, follow, max-image-preview:large"/><link rel="preload" as="image" href="/assets/ai-data/cleaning-validation/data-cleaning-preparation/data-cleaning-preparation-services-hero.webp" type="image/webp" fetchPriority="high"/><script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
  <PreparationMotionStyles/>
  <ServiceHero tone="light" compactHeadline preHeadline="Traceable Data Preparation" headline="Data Cleaning & Preparation Services" headlineAccent="for AI Training Data" subtext="Remove duplicates, repair encoding, strip noise and standardise inconsistent values—with every change logged and reversible, and the effect on your data distribution reported because cleaning is never neutral." ctaText="Get a Free Dataset Audit" ctaLink="/free-pilot" secondaryCtaText="Talk to a Data Specialist" secondaryCtaLink="/contact-us" imageSrc="/assets/ai-data/cleaning-validation/data-cleaning-preparation/data-cleaning-preparation-services-hero.webp" imageAlt="Data specialist reviewing an illustrative cleaning change log with before and after values side by side" imageWidth={1200} imageHeight={800} trustStats={[{value:"Logged",label:"Attributable + reversible"},{value:"Impact",label:"Distribution reported"},{value:"30+",label:"Global languages + Indian depth"}]} rotatingBadges={[{icon:GitCompareArrows,title:"Before / after",subtitle:"Original · repaired · rule",color:"hsl(170 82% 38%)"},{icon:FileClock,title:"Change log",subtitle:"Counted · attributable · reversible",color:"hsl(28 90% 48%)"},{icon:Languages,title:"Script-aware",subtitle:"Global · Indian · code-mixed",color:"hsl(190 76% 40%)"}]} bottomBadge={{iconText:"QA",title:"Nothing changed silently",subtitle:"Profile · repair · verify"}}/>
  <PreparationTrustStrip/><PreparationDefinition/><CleaningPillars/><MissingOutliersStructure/><DistributionImpact/><WhenNotToClean/><IndicEncoding/><PreparationProcess/><DeliverablesAutomation/><FormatsSecurityEngagement/><CostRelatedWhy/><PreparationFAQ/>
  <ServiceCTA headline="Find Out What's Wrong With Your Data" subtext="Share a representative sample. We'll return duplication rate, missingness by field, encoding integrity, format variance and outlier counts before anything gets changed." ctaText="Get a Free Dataset Audit" ctaLink="/free-pilot" secondaryCtaText="Talk to a Data Specialist" secondaryCtaLink="/contact-us" note="Start with a measured profile"/>
</AIDataServicesLayout>;

export default DataCleaningPreparationPage;
