export const preparationFaqs = [
  ["What is data cleaning?", "Data cleaning makes a dataset structurally sound: records are well-formed, values use consistent formats, duplicates are resolved and character encoding is correct. It makes data well-formed, which is different from making it true."],
  ["What is the difference between data cleaning and data validation?", "Cleaning makes data well-formed. Validation checks whether it is correct. A record can be perfectly formatted, fully populated and correctly typed while being completely wrong."],
  ["How do you detect duplicates?", "We combine exact hashes, fuzzy and token similarity, MinHash and LSH, semantic similarity, perceptual hashes for images and composite keys for records. The method depends on the modality and scale."],
  ["How do you decide what counts as a duplicate?", "It is a use-case decision, not a universal fact. We agree the definition and tune thresholds on a reviewed sample before removing or merging anything."],
  ["Which record survives when duplicates are merged?", "Survivorship rules are defined before processing: most complete, most recent, most authoritative, or a merged record. Discarded versions remain in the change log."],
  ["How should missing values be handled?", "Treatment depends on why a value is missing. Completely random missingness may be safely dropped; missingness explained by observed fields may support conditional imputation; missingness tied to the absent value itself often needs an explicit missing category."],
  ["Do you remove outliers?", "Not automatically. An outlier is unusual, not necessarily wrong. Statistical flags are reviewed against domain context; confirmed errors are corrected or flagged, while real rare values are retained and reported."],
  ["Can data cleaning introduce bias?", "Yes. Dropping incomplete records, removing outliers or imputing values can change class balance, variance and group representation. We report distribution impact before and after so the shift is visible."],
  ["What is mojibake and can you fix it?", "Mojibake is text decoded with the wrong character encoding. It is often repairable when the original encoding can be identified. We also address double-encoded UTF-8, byte-order marks and replacement characters."],
  ["What is Unicode normalisation and why does it matter?", "Visually identical characters can have different code-point sequences. Without consistent normalisation, matching, search and deduplication can treat them as different strings."],
  ["Do you handle Indic scripts?", "Yes. Script-aware rules preserve meaningful joiners, non-joiners, nukta and matra behaviour, and address legacy encodings, mixed scripts and transliteration variance with native-language review across major Indian regional languages."],
  ["What happens with ambiguous dates such as 03/04/2026?", "We flag rather than guess. If the source convention cannot be established, choosing one creates a clean-looking but potentially incorrect dataset."],
  ["Do you modify our original data?", "Never silently and never in place. Originals are preserved, every change records the old value, new value and rule, and transformations can be reversed."],
  ["What formats do you work with?", "CSV, TSV, Excel, Parquet, JSON, JSONL, XML, text corpora, database exports and connections, annotation formats such as COCO, YOLO, Pascal VOC and CoNLL, plus media collections with metadata."],
  ["How much does data cleaning cost?", "Cost depends on size, modality, sources, defect density, rule complexity, human adjudication, language and script coverage, domain expertise, correction depth, security and turnaround. Profiling provides the counts needed for an honest quote."],
  ["How do we start?", "Start with a sample profiling pass. You receive duplication rate, missingness by field, encoding integrity, format variance and outlier counts before anything is changed."],
] as const;

export const preparationOffers = ["Deduplication", "Character Encoding Repair", "Unicode Normalisation", "Noise and Boilerplate Removal", "OCR Artefact Cleanup", "Consistency Normalization", "Missing Value Analysis and Treatment", "Outlier Detection and Adjudication", "Schema Conformance and Structural Repair", "Indic Script Encoding Repair"] as const;
