import { Helmet } from "react-helmet-async";
import { FileSearch2, Filter, Languages } from "lucide-react";
import AIDataServicesLayout from "../../shared/AIDataServicesLayout";
import SEOHead from "../../shared/SEOHead";
import ServiceCTA from "../../shared/ServiceCTA";
import ServiceHero from "../../shared/ServiceHero";
import { curationFaqs } from "./LlmCurationContent";
import { CostRelatedWhy, CurationDefinition, CurationFAQ, CurationMotionStyles, CurationProcess, CurationStack, CurationTrustStrip, Decontamination, DeliverablesAndJudgement, LanguagesFormatsSecurity, OverFiltering, ProvenanceAndSynthetic } from "./LlmCurationCoreSections";

const canonical="https://www.eqourse.com/ai-data-services/cleaning-validation/llm-data-curation";
const offers=["Corpus Deduplication","Quality Filtering","Boilerplate and Template Removal","Benchmark Decontamination","PII Scrubbing at Corpus Scale","Toxicity and Safety Filtering","Language Identification and Filtering","Synthetic Content Detection","Licence and Provenance Review","Domain Composition Analysis"];
const schema={"@context":"https://schema.org","@graph":[{"@type":"Service","@id":`${canonical}#service`,name:"LLM Training Data Curation Services",serviceType:"LLM Corpus Curation and Data Preparation",url:canonical,description:"Corpus curation for LLM pre-training and fine-tuning including deduplication, quality filtering, benchmark decontamination, privacy review, provenance documentation and domain composition analysis, with human review of retained and filtered-out samples.",provider:{"@type":"Organization",name:"eQOURSE",url:"https://www.eqourse.com/",address:[{"@type":"PostalAddress",addressCountry:"IN"},{"@type":"PostalAddress",addressCountry:"SG"}]},areaServed:"Worldwide",availableLanguage:["en","hi","bn","ta","te","mr","gu","kn","ml","pa","or","as","ur"],isPartOf:{"@type":"Service","@id":"https://www.eqourse.com/ai-data-services/cleaning-validation#service",name:"Data Cleaning & Validation Services",url:"https://www.eqourse.com/ai-data-services/cleaning-validation"},hasOfferCatalog:{"@type":"OfferCatalog",name:"LLM Training Data Curation Services",itemListElement:offers.map(name=>({"@type":"Offer",itemOffered:{"@type":"Service",name}}))}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://www.eqourse.com/"},{"@type":"ListItem",position:2,name:"AI Data Services",item:"https://www.eqourse.com/ai-data-services"},{"@type":"ListItem",position:3,name:"Data Cleaning & Validation",item:"https://www.eqourse.com/ai-data-services/cleaning-validation"},{"@type":"ListItem",position:4,name:"LLM Data Curation",item:canonical}]},{"@type":"FAQPage",mainEntity:curationFaqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]};

const LlmDataCurationPage=()=> <AIDataServicesLayout breadcrumbs={[{label:"AI Data Services",href:"/ai-data-services"},{label:"Data Cleaning & Validation",href:"/ai-data-services/cleaning-validation"},{label:"LLM Data Curation"}]}>
  <SEOHead title="LLM Training Data Curation Services | eQOURSE" description="LLM corpus deduplication, quality filtering and benchmark decontamination—with provenance review and human checks of filtered-out content." canonical={canonical} keywords="LLM training data curation, pretraining data curation services, LLM data preparation services, LLM corpus curation, benchmark decontamination, corpus deduplication" ogImage="https://www.eqourse.com/assets/ai-data/cleaning-validation/llm-data-curation/llm-data-curation-og.webp"/>
  <Helmet><meta name="robots" content="index, follow, max-image-preview:large"/><link rel="preload" as="image" href="/assets/ai-data/cleaning-validation/llm-data-curation/llm-data-curation-services-hero.webp" type="image/webp" fetchPriority="high"/><script type="application/ld+json">{JSON.stringify(schema)}</script></Helmet>
  <CurationMotionStyles/>
  <ServiceHero tone="light" preHeadline="Corpus Quality Before Training" headline="LLM Training Data" headlineAccent="Curation Services" subtext="Prepare corpora for LLM pre-training and fine-tuning through deduplication, quality filtering, benchmark decontamination, privacy handling, provenance review and domain balancing—with human review of what filters removed, not only what survived." ctaText="Get a Free Corpus Audit" ctaLink="/free-pilot" secondaryCtaText="Talk to a Data Specialist" secondaryCtaLink="/contact-us" imageSrc="/assets/ai-data/cleaning-validation/llm-data-curation/llm-data-curation-services-hero.webp" imageAvifSrc="/assets/ai-data/cleaning-validation/llm-data-curation/llm-data-curation-services-hero.avif" imageAlt="Specialist reviewing documents removed by a corpus quality filter alongside retention rates by domain" imageWidth={1200} imageHeight={800} trustStats={[{value:"Both ways",label:"Retained + removed reviewed"},{value:"Eval-safe",label:"Capability, not memory"},{value:"30+",label:"Global languages + Indian depth"}]} rotatingBadges={[{icon:Filter,title:"Dual-set review",subtitle:"Retained · discarded · tuned",color:"hsl(170 82% 38%)"},{icon:FileSearch2,title:"Decontamination",subtitle:"Exact · n-gram · fuzzy",color:"hsl(28 90% 48%)"},{icon:Languages,title:"Language-aware",subtitle:"Global · Indian · code-mixed",color:"hsl(190 76% 40%)"}]} bottomBadge={{iconText:"LLM",title:"Corpus made accountable",subtitle:"Source · quality · lineage"}}/>
  <CurationTrustStrip/><CurationDefinition/><CurationStack/><OverFiltering/><Decontamination/><ProvenanceAndSynthetic/><CurationProcess/><DeliverablesAndJudgement/><LanguagesFormatsSecurity/><CostRelatedWhy/><CurationFAQ/>
  <ServiceCTA headline="Find Out What's Actually in Your Corpus" subtext="Share a representative slice. We'll return duplication rate, estimated quality distribution, benchmark contamination and domain composition—before anything gets filtered." ctaText="Get a Free Corpus Audit" ctaLink="/free-pilot" secondaryCtaText="Talk to a Data Specialist" secondaryCtaLink="/contact-us" note="Start with a corpus profile"/>
</AIDataServicesLayout>;
export default LlmDataCurationPage;
