import { type ReactNode } from "react";
import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import { motion, useReducedMotion } from "framer-motion";
import { ArrowRight, Check, Database, FileCheck2, Gauge, RotateCcw, ShieldCheck, UsersRound } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import AIDataServicesLayout from "../../shared/AIDataServicesLayout";
import SEOHead from "../../shared/SEOHead";
import { collectionMethods, diversityAxes, failureModes, faqs, programmeSteps, qualityDimensions } from "./HumanDemonstrationsContent";

const PATH = "/robotics-training-data-services/human-demonstrations";
const CANONICAL = `https://www.eqourse.com${PATH}`;
const ASSET_ROOT = "/assets/ai-data/robotics/human-demonstrations";
const CONTACT = `/contact-us?service=human-demonstrations&source=${PATH.slice(1)}#contact-form`;

const serviceSchema = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Service", "@id": `${CANONICAL}#service`, name: "Human Demonstration Data Collection for Robotics",
      serviceType: "Teleoperation and egocentric demonstration data collection for robot learning", url: CANONICAL,
      description: "Teleoperated and egocentric human demonstration data collection for Physical AI and robot learning, with designed diversity, failure and recovery episodes, per-episode QA and LeRobot and RLDS-compatible delivery.",
      provider: { "@type": "Organization", name: "eQOURSE", url: "https://www.eqourse.com/" },
      areaServed: ["IN", "SG", "US", "GB", "AE", "AU", "EU", "JP", "KR"],
      isPartOf: { "@id": "https://www.eqourse.com/robotics-training-data-services#service" },
      hasOfferCatalog: {
        "@type": "OfferCatalog", name: "Demonstration data collection services",
        itemListElement: ["Teleoperation data collection", "Handheld and wrist-mounted rig collection", "Bimanual leader-follower demonstration capture", "VR teleoperation data collection", "Egocentric human demonstration video collection", "Failure and recovery episode collection", "LeRobot and RLDS dataset delivery"].map((name) => ({ "@type": "Offer", itemOffered: { "@type": "Service", name } })),
      },
    },
    {
      "@type": "BreadcrumbList", itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: "https://www.eqourse.com/" },
        { "@type": "ListItem", position: 2, name: "Robotics Training Data", item: "https://www.eqourse.com/robotics-training-data-services" },
        { "@type": "ListItem", position: 3, name: "Human Demonstrations", item: CANONICAL },
      ],
    },
    { "@type": "FAQPage", mainEntity: faqs.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) },
  ],
};

const Reveal = ({ children, className = "", delay = 0 }: { children: ReactNode; className?: string; delay?: number }) => {
  const reduce = useReducedMotion();
  return <motion.div className={className} initial={reduce ? false : { opacity: 0, y: 30 }} whileInView={reduce ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ duration: .65, delay, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>;
};

const Intro = ({ eyebrow, title, accent, body, light = false }: { eyebrow: string; title: string; accent?: string; body?: string; light?: boolean }) => <div className="max-w-3xl">
  <p className={`text-xs font-bold uppercase tracking-[.18em] ${light ? "text-teal-300" : "text-primary"}`}>{eyebrow}</p>
  <h2 className={`mt-4 font-heading text-3xl font-bold leading-tight md:text-5xl ${light ? "text-white" : "text-[#15183f]"}`}>{title} {accent && <span className="text-primary">{accent}</span>}</h2>
  {body && <p className={`mt-5 text-base leading-7 md:text-lg ${light ? "text-white/68" : "text-muted-foreground"}`}>{body}</p>}
</div>;

const DataTable = ({ headers, rows, caption }: { headers: string[]; rows: readonly (readonly string[])[]; caption: string }) => <div className="mt-10 overflow-x-auto rounded-[1.5rem] border border-slate-200 bg-white shadow-[0_24px_70px_rgba(17,31,59,.07)]">
  <table className="w-full min-w-[760px] border-collapse text-left text-sm">
    <caption className="sr-only">{caption}</caption>
    <thead className="bg-[#12223b] text-white"><tr>{headers.map((h) => <th key={h} scope="col" className="px-5 py-4 font-semibold">{h}</th>)}</tr></thead>
    <tbody>{rows.map((row, i) => <tr key={row[0]} className={i % 2 ? "bg-slate-50/75" : "bg-white"}>{row.map((cell, j) => j === 0 ? <th key={cell} scope="row" className="min-w-44 border-t border-slate-200 px-5 py-4 font-bold text-[#15183f]">{cell}</th> : <td key={cell} className="border-t border-slate-200 px-5 py-4 leading-6 text-slate-600">{cell}</td>)}</tr>)}</tbody>
  </table>
</div>;

const DiversityGraphic = () => <svg viewBox="0 0 920 480" role="img" aria-labelledby="diversity-title diversity-desc" className="h-auto w-full text-primary">
  <title id="diversity-title">Illustrative comparison of repeated episodes and task diversity</title>
  <desc id="diversity-desc">Episodes of one task rise quickly then flatten around 500 to 1,000, while distinct task types continue to add value.</desc>
  <defs><linearGradient id="curveB" x1="0" x2="1"><stop stopColor="#13ae96"/><stop offset="1" stopColor="#74e3c4"/></linearGradient></defs>
  <rect x="1" y="1" width="918" height="478" rx="30" fill="#0f2038"/>
  <g transform="translate(82 52)">
    <path d="M0 330H748M0 330V10" stroke="#fff" strokeOpacity=".18"/>
    <path d="M0 318C90 105 186 77 282 70S530 66 748 64" fill="none" stroke="#ffae35" strokeWidth="8" strokeLinecap="round"/>
    <path d="M0 320C98 284 190 238 292 205S512 126 748 34" fill="none" stroke="url(#curveB)" strokeWidth="8" strokeLinecap="round"/>
    <circle cx="282" cy="70" r="10" fill="#ffae35"/><path d="M282 70V126H174" fill="none" stroke="#ffae35" strokeDasharray="5 5"/>
    <text x="174" y="151" fill="#ffd58d" fontSize="20" fontWeight="700">~500–1,000</text><text x="174" y="175" fill="#fff" fillOpacity=".6" fontSize="15">marginal depth flattens</text>
    <circle cx="684" cy="59" r="10" fill="#63dbc0"/><text x="470" y="30" fill="#8fe8d2" fontSize="18" fontWeight="700">still climbing at thousands</text>
    <text x="535" y="102" fill="#ffd58d" fontSize="17" fontWeight="700">episodes of one task</text>
    <text x="505" y="222" fill="#8fe8d2" fontSize="17" fontWeight="700">distinct task types</text>
    <text x="286" y="382" fill="#fff" fontSize="20" fontWeight="700">same budget, different shape</text>
    <text x="0" y="414" fill="#fff" fillOpacity=".48" fontSize="14">Illustrative curves; the 500–1,000 guidance reflects current published practice.</text>
  </g>
</svg>;

const RecoveryGraphic = () => {
  const reduce = useReducedMotion();
  const pathMotion = reduce ? {} : { pathLength: [0, 1] };
  return <svg viewBox="0 0 980 430" role="img" aria-labelledby="recovery-title recovery-desc" className="h-auto w-full">
    <title id="recovery-title">Success, recovery and dead-end demonstration trajectories</title><desc id="recovery-desc">One trajectory reaches the goal, one slips and recovers, and one ends as a labelled dead end.</desc>
    <rect x="1" y="1" width="978" height="428" rx="30" fill="#f5faf9" stroke="#b9ddd6"/>
    <text x="58" y="60" fill="#13213a" fontSize="17" fontWeight="700">START</text><circle cx="84" cy="210" r="18" fill="#15243d"/>
    <circle cx="874" cy="210" r="34" fill="none" stroke="#13ae96" strokeWidth="8"/><circle cx="874" cy="210" r="9" fill="#13ae96"/><text x="840" y="274" fill="#087f70" fontSize="17" fontWeight="700">GOAL</text>
    <motion.path d="M106 180C310 80 610 92 838 190" fill="none" stroke="#13ae96" strokeWidth="8" strokeLinecap="round" initial={reduce ? undefined : { pathLength: 0 }} whileInView={pathMotion} viewport={{ once: true }} transition={{ duration: 1.5 }}/>
    <text x="390" y="83" fill="#087f70" fontSize="17" fontWeight="700">clean success</text>
    <motion.path d="M106 211C286 198 332 315 456 311S624 222 838 211" fill="none" stroke="#ff9d13" strokeWidth="8" strokeLinecap="round" initial={reduce ? undefined : { pathLength: 0 }} whileInView={pathMotion} viewport={{ once: true }} transition={{ duration: 1.7, delay: .2 }}/>
    <circle cx="358" cy="291" r="9" fill="#ff9d13"/><text x="300" y="350" fill="#b75d00" fontSize="17" fontWeight="700">slip</text><text x="548" y="280" fill="#b75d00" fontSize="17" fontWeight="700">recovery</text>
    <motion.path d="M106 242C224 287 304 361 474 362" fill="none" stroke="#718096" strokeWidth="7" strokeDasharray="11 11" strokeLinecap="round" initial={reduce ? undefined : { pathLength: 0 }} whileInView={pathMotion} viewport={{ once: true }} transition={{ duration: 1.4, delay: .35 }}/>
    <path d="M462 350L486 374M486 350L462 374" stroke="#718096" strokeWidth="7"/><text x="515" y="369" fill="#475569" fontSize="17" fontWeight="700">dead end — labelled, not discarded</text>
  </svg>;
};

const HumanDemonstrationsPage = () => {
  const reduce = useReducedMotion();
  return <AIDataServicesLayout breadcrumbs={[{ label: "Robotics Training Data", href: "/robotics-training-data-services" }, { label: "Human Demonstrations" }]}>
    <SEOHead title="Human Demonstration Data Collection for Robotics | eQOURSE" description="Teleoperation and egocentric human demonstration data for robot learning with multi-rig collection, failure-recovery episodes, per-episode QA, LeRobot and RLDS delivery." canonical={CANONICAL} keywords="human demonstration data for robotics, teleoperation data collection services, robot demonstration data, embodied AI data collection, robot training data collection, LeRobot dataset format" ogImage="https://www.eqourse.com/assets/ai-data/robotics/human-demonstrations/og-human-demonstrations.jpg" />
    <Helmet><meta name="robots" content="index, follow"/><script type="application/ld+json">{JSON.stringify(serviceSchema)}</script></Helmet>
    <main className="overflow-hidden bg-[#f6faf9]">
      <section className="relative isolate min-h-[720px] overflow-hidden bg-[#0d1b30] text-white md:min-h-[760px]">
        <motion.picture className="absolute inset-0 -z-20" initial={reduce ? false : { opacity: 0, scale: 1.04 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 1.1 }}>
          <source srcSet={`${ASSET_ROOT}/human-demonstrations-hero.avif`} type="image/avif"/><source srcSet={`${ASSET_ROOT}/human-demonstrations-hero.webp`} type="image/webp"/>
          <img src={`${ASSET_ROOT}/human-demonstrations-hero.webp`} alt="Operator recording a teleoperated manipulation demonstration on a leader-follower rig" width="1600" height="900" loading="eager" decoding="async" {...{ fetchpriority: "high" }} className="h-full w-full object-cover object-[64%_center]"/>
        </motion.picture>
        <div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(9,20,38,.97)_0%,rgba(9,20,38,.88)_38%,rgba(9,20,38,.2)_78%)]"/>
        <div className="absolute inset-0 -z-10 opacity-25 [background-image:linear-gradient(rgba(91,230,197,.16)_1px,transparent_1px),linear-gradient(90deg,rgba(91,230,197,.16)_1px,transparent_1px)] [background-size:64px_64px]"/>
        <div className="container mx-auto flex min-h-[720px] items-center px-4 pb-28 pt-20 md:min-h-[760px]">
          <motion.div className="max-w-3xl" initial={reduce ? false : { opacity: 0, y: 35 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .85 }}>
            <p className="inline-flex items-center gap-2 rounded-full border border-teal-300/30 bg-teal-300/10 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-teal-200"><span className="h-2 w-2 rounded-full bg-teal-300"/> Human-operated · policy-ready</p>
            <h1 className="mt-7 max-w-3xl font-heading text-4xl font-bold leading-[1.04] sm:text-5xl md:text-7xl">Human Demonstration Data <span className="text-[#51dfbd]">for Robot Learning</span></h1>
            <p className="mt-6 max-w-2xl text-base leading-7 text-white/72 md:text-xl md:leading-8">Teleoperated and egocentric demonstrations collected by trained operators across varied tasks, objects and environments—including the failure-and-recovery episodes most datasets discard.</p>
            <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to={CONTACT}><Button size="lg" className="h-13 px-7">Scope a Collection Programme <ArrowRight className="ml-2 h-4 w-4"/></Button></Link><a href="#how-many" className="inline-flex h-13 items-center justify-center rounded-lg border border-white/25 bg-white/5 px-7 font-semibold text-white backdrop-blur transition hover:bg-white/12">How many episodes do you need?</a></div>
          </motion.div>
        </div>
        <div className="absolute inset-x-0 bottom-0 border-t border-white/10 bg-[#091526]/80 backdrop-blur-xl"><div className="container mx-auto grid grid-cols-2 px-4 md:grid-cols-4">{["Multi-rig collection", "Failure + recovery", "Per-episode QA", "LeRobot · RLDS"].map((x) => <div key={x} className="border-white/10 px-3 py-5 text-center text-xs font-bold uppercase tracking-[.12em] text-white/75 md:border-r md:text-sm first:md:border-l">{x}</div>)}</div></div>
      </section>

      <section className="bg-white py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><Reveal><Intro eyebrow="The real bottleneck" title="The rigs are available." accent="Sustained human quality is not."/><div className="mt-8 space-y-5 text-lg leading-8 text-slate-600"><p>Vision-language-action architectures are advancing quickly, and some capture rigs cost less than a single workstation. But every useful episode still requires a person to perform a physical task well while actions, states and observations stay aligned.</p><p><strong className="text-[#15183f]">The constraint on Physical AI is trained human hours at sustained quality.</strong> That is a workforce operations problem: staffing, certification, rotation, environment control and episode-level review.</p></div></Reveal><Reveal className="rounded-[2rem] bg-[#12223b] p-8 text-white md:p-10" delay={.1}><Gauge className="h-9 w-9 text-teal-300"/><p className="mt-8 font-heading text-3xl font-bold leading-tight">A capture rig can cost around <span className="text-[#ffb547]">$500.</span> A trained operator working a full year does not.</p><p className="mt-5 leading-7 text-white/65">Where and how collection is staffed determines whether a programme reaches 100,000 episodes or stalls at 3,000.</p></Reveal></div></section>

      <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Collection methods" title="Choose fidelity, throughput" accent="and embodiment fit" body="There is no universally correct rig. Published practice figures below are directional—not eQOURSE throughput guarantees. We scope only the methods available for your programme."/><p className="mt-3 text-xs text-slate-500">Last reviewed: August 2026</p><DataTable headers={["Method", "What it is", "Typical published throughput", "Best for", "Trade-off"]} rows={collectionMethods} caption="Comparison of human demonstration collection methods"/></Reveal></div></section>

      <section id="how-many" className="scroll-mt-32 bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Dataset shape" title="Breadth keeps paying after" accent="depth flattens" body="Current practice suggests the marginal value of repeating one task declines around 500–1,000 demonstrations, while new task types keep adding value much longer."/><p className="mt-3 text-xs text-slate-500">Last reviewed: August 2026</p></Reveal><div className="mt-12 grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><Reveal><DiversityGraphic/></Reveal><Reveal className="lg:pl-5" delay={.08}><p className="font-heading text-3xl font-bold leading-tight text-[#15183f]">Don’t buy 5,000 episodes of one task. Buy 800 each across six tasks.</p><p className="mt-5 text-lg leading-8 text-slate-600">Same budget. Varied environments, objects, operators and initial conditions. A policy that has a chance to generalise instead of memorise.</p><div className="mt-8 border-l-4 border-primary bg-primary/[.06] p-5 text-sm leading-6 text-slate-700"><strong>Our position:</strong> we would rather propose a broader programme than a bigger one. The diversity split and its rationale belong in the scope document.</div></Reveal></div><Reveal><DataTable headers={["Axis", "What to vary", "Why it matters"]} rows={diversityAxes} caption="Diversity axes for robot demonstration datasets"/></Reveal></div></section>

      <section className="bg-[#0e1b30] py-20 text-white md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro light eyebrow="Failure is data" title="The episodes almost nobody collects" body="Operators naturally reset after a slip. We deliberately preserve the deviation, the correction and the cases that cannot be recovered."/></Reveal><div className="mt-12 grid gap-10 lg:grid-cols-[1.08fr_.92fr] lg:items-center"><Reveal><RecoveryGraphic/></Reveal><Reveal delay={.08}><div className="space-y-5">{["Grasp failures and re-grasps", "Mid-task perturbations", "Partial completion and resumption", "Near-miss corrections", "Genuine labelled dead ends", "Multiple valid strategies"].map((x, i) => <div key={x} className="flex items-center gap-4 border-b border-white/10 pb-5"><span className="font-mono text-xs text-teal-300">0{i + 1}</span><p className="font-semibold text-white/85">{x}</p></div>)}</div><p className="mt-8 text-sm leading-7 text-white/62"><strong className="text-teal-300">An operations decision, not a hardware feature.</strong> A well-executed failure is treated as a successful episode when it follows the brief and is labelled honestly.</p></Reveal></div></div></section>

      <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Episode integrity" title="What makes a demonstration" accent="usable" body="A visually convincing episode can still be harmful training data. These are the checks that decide whether it ships."/><DataTable headers={["Quality dimension", "What good looks like", "What it costs when wrong"]} rows={qualityDimensions} caption="Human demonstration episode quality dimensions"/></Reveal></div></section>

      <section className="bg-white py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-2 lg:items-center"><Reveal className="overflow-hidden rounded-[2rem]"><picture><source srcSet={`${ASSET_ROOT}/collection-floor.avif`} type="image/avif"/><source srcSet={`${ASSET_ROOT}/collection-floor.webp`} type="image/webp"/><img src={`${ASSET_ROOT}/collection-floor.webp`} alt="Multiple task stations dressed with varied surfaces, objects and lighting for demonstration diversity" width="1200" height="675" loading="lazy" decoding="async" className="aspect-video h-full w-full object-cover"/></picture></Reveal><Reveal delay={.1}><Intro eyebrow="The operational moat" title="Operator quality is" accent="an operations problem"/><div className="mt-7 space-y-4">{["Managed session lengths with enforced rotation", "Calibration tasks and operator certification", "Multiple operators per task by design", "Per-episode QA instead of batch sampling", "Per-operator quality tracked over time", "Ergonomic caps for VR and exoskeleton work"].map((x) => <div key={x} className="flex gap-3 text-slate-700"><Check className="mt-1 h-5 w-5 shrink-0 text-primary"/><span className="leading-7">{x}</span></div>)}</div><div className="mt-8 rounded-2xl bg-[#15183f] p-6 text-white"><p className="font-heading text-2xl font-bold"><span className="text-teal-300">500+ trained specialists</span> is the operating advantage.</p><p className="mt-3 text-sm leading-6 text-white/65">Rigs can be bought quickly. A certified, scheduled and quality-managed operator bench takes time to build.</p></div></Reveal></div></section>

      <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><Reveal><Intro eyebrow="Interoperable delivery" title="Data you cannot load" accent="is data you do not have" body="The target format and conventions are agreed at scoping and validated in your own loader before volume collection begins."/><div className="mt-8 flex flex-wrap gap-2">{["LeRobot", "RLDS", "Open X-Embodiment", "HDF5", "Raw synchronised streams", "Metadata sidecar"].map((x) => <span key={x} className="rounded-full border border-primary/20 bg-white px-4 py-2 text-sm font-semibold text-[#15183f]">{x}</span>)}</div></Reveal><Reveal className="rounded-[2rem] bg-[#12223b] p-8 text-white md:p-10" delay={.1}><Database className="h-8 w-8 text-teal-300"/><div className="mt-7 grid gap-7 sm:grid-cols-2"><div><h3 className="font-heading text-xl font-bold">Action representation</h3><p className="mt-3 text-sm leading-6 text-white/62">Absolute versus delta is written into the manifest, documentation and pilot handover. Published work has documented 0% success when this convention was confused.</p></div><div><h3 className="font-heading text-xl font-bold">Proprioceptive state</h3><p className="mt-3 text-sm leading-6 text-white/62">Fields, order, frame and rate are explicit. Published evaluation work has documented a 55-point swing from the wrong source.</p></div></div><p className="mt-8 border-t border-white/12 pt-6 text-sm font-semibold text-teal-200">Published figures illustrate why conventions must be validated; they are not claims about a specific client model.</p></Reveal></div></div></section>

      <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Pilot-gated scale" title="How a collection programme" accent="runs" body="Seven controlled steps turn a task idea into rolling, training-ready episodes. Step five is the gate."/></Reveal><div className="mt-12 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{programmeSteps.map(([n, title, time, text], i) => <Reveal key={n} className={`relative min-h-56 rounded-2xl border p-6 ${i === 4 ? "border-amber-400 bg-[#fff7e8] ring-4 ring-amber-100 lg:col-span-2" : "border-slate-200 bg-[#f6faf9]"}`} delay={i * .035}><div className="flex items-center justify-between"><span className={`font-mono text-sm font-bold ${i === 4 ? "text-amber-700" : "text-primary"}`}>{n}</span><span className="text-xs font-semibold text-slate-500">{time}</span></div><h3 className="mt-8 font-heading text-xl font-bold text-[#15183f]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p>{i === 4 && <p className="mt-5 text-xs font-bold uppercase tracking-[.12em] text-amber-700">Nothing scales until this clears</p>}</Reveal>)}</div><p className="mt-8 text-center text-sm text-slate-600">Setup through a cleared pilot typically takes <strong className="text-[#15183f]">about four weeks</strong>. Volume is then quoted in episodes per week with rolling delivery.</p></div></section>

      <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Delivery package" title="What you" accent="get"/></Reveal><div className="mt-10 grid gap-px overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-4">{[[Database,"Episode dataset"],[FileCheck2,"Per-episode metadata"],[RotateCcw,"Failure + recovery subset"],[Gauge,"Diversity coverage report"],[ShieldCheck,"QA records"],[FileCheck2,"Convention documentation"],[Check,"Pilot validation record"],[Database,"Rejected-episode log"]].map(([Icon, title]) => { const IconComponent = Icon as typeof Database; return <article key={title as string} className="bg-white p-6"><IconComponent className="h-6 w-6 text-primary"/><h3 className="mt-8 font-heading font-bold text-[#15183f]">{title as string}</h3></article>; })}</div></div></section>

      <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Failure prevention" title="Where demonstration collection" accent="goes wrong"/><DataTable headers={["Failure", "What happens", "How we avoid it"]} rows={failureModes} caption="Common robot demonstration collection failures and controls"/></Reveal></div></section>

      <section className="bg-[#15183f] py-20 text-white md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro light eyebrow="Clear boundaries" title="What we do—and what we do not"/></Reveal><div className="mt-12 grid gap-8 lg:grid-cols-2"><Reveal className="rounded-[2rem] border border-teal-300/20 bg-teal-300/[.07] p-8"><h3 className="font-heading text-2xl font-bold text-teal-200">We collect, QA and deliver</h3><ul className="mt-7 space-y-4 text-white/72">{["Purpose-built demonstration episodes", "Documented task and diversity design", "Exclusive client data ownership", "Consent-led capture and secure handling", "Pilot-validated formats and conventions"].map((x) => <li key={x} className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-teal-300"/>{x}</li>)}</ul></Reveal><Reveal className="rounded-[2rem] border border-white/12 p-8" delay={.08}><h3 className="font-heading text-2xl font-bold">We do not overclaim</h3><ul className="mt-7 space-y-4 text-white/62">{["We do not train your robot policies", "We do not sell episode count without dataset shape", "We do not claim rigs that are unavailable", "We do not scale before the pilot loads", "We do not reuse or resell your data"].map((x) => <li key={x} className="border-b border-white/10 pb-4">{x}</li>)}</ul></Reveal></div></div></section>

      <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Engagement models" title="Start at the scale" accent="that proves the workflow"/></Reveal><div className="mt-10 grid gap-5 md:grid-cols-2">{[["Pilot programme","One or two tasks, limited diversity and full format validation in 4–5 weeks."],["Task collection programme","A designed task set, diversity split and failure protocol delivered on a rolling schedule."],["Egocentric diversity layer","Large-scale human video capture without a robot, alongside or ahead of teleoperation."],["Dedicated capacity","A reserved operator pool and rig configuration with agreed weekly throughput."]].map(([title, text], i) => <Reveal key={title} className="group border-t border-slate-300 py-7" delay={i * .05}><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="mt-5 font-heading text-2xl font-bold text-[#15183f]">{title}</h3><p className="mt-3 max-w-xl leading-7 text-slate-600">{text}</p></Reveal>)}</div><Link to={CONTACT} className="mt-8 inline-flex items-center gap-2 font-bold text-primary">Scope a collection programme <ArrowRight className="h-4 w-4"/></Link></div></section>

      <section className="bg-white py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Why eQOURSE" title="Human operations designed" accent="for data quality"/></Reveal><div className="mt-12 grid gap-px overflow-hidden rounded-[2rem] border border-slate-200 bg-slate-200 md:grid-cols-2 lg:grid-cols-3">{[[UsersRound,"500+ trained specialists","Rotation, certification and per-operator quality tracking."],[Gauge,"Viable collection economics","India and Singapore operations for sustained, managed capacity."],[RotateCcw,"Recovery by design","Failure and recovery are planned, not found by accident."],[Database,"Regional collection network","Real environments and diversity no single lab can reproduce."],[FileCheck2,"Per-episode QA","Every episode is reviewed before delivery."],[ShieldCheck,"ISO 9001 & 27001","Exclusive ownership and restricted-environment handling."]].map(([Icon,title,text])=>{const I=Icon as typeof UsersRound;return <article key={title as string} className="bg-[#f8fbfa] p-7"><I className="h-7 w-7 text-primary"/><h3 className="mt-7 font-heading text-xl font-bold text-[#15183f]">{title as string}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text as string}</p></article>})}</div></div></section>

      <section className="py-20 md:py-28"><div className="container mx-auto max-w-7xl px-4"><Reveal><Intro eyebrow="Robotics service map" title="One programme, five" accent="different deliverables" body="The categories are separated by what they produce, so clients and search engines can understand where each responsibility begins."/></Reveal><div className="mt-10 divide-y divide-slate-200 border-y border-slate-200">{[["Human demonstrations","We create the episodes.",PATH,true],["Multimodal sensor data","We capture and align the signals.","",false],["3D & spatial annotation","We label the world.","",false],["VLA evaluation","We score the model.","",false],["Deployment validation","We verify it in place.","",false]].map(([title,text,to,live],i)=><div key={title as string} className="grid gap-2 py-6 md:grid-cols-[3rem_1fr_1fr_auto] md:items-center"><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="font-heading text-xl font-bold text-[#15183f]">{title as string}</h3><p className="text-slate-600">{text as string}</p>{live ? <Link to={to as string} aria-current="page" className="text-sm font-bold text-primary">Current page</Link> : <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">Page coming next</span>}</div>)}</div><div className="mt-10 flex flex-wrap gap-3"><Link to="/robotics-training-data-services" className="rounded-full border border-primary/25 bg-white px-5 py-3 text-sm font-bold text-primary">Robotics training data services</Link><Link to="/ai-data-services/data-collection" className="rounded-full border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-[#15183f]">AI data collection</Link><Link to="/ai-data-services/annotation-labeling/3d-point-cloud-lidar-annotation" className="rounded-full border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-[#15183f]">3D Point Cloud & LiDAR Annotation</Link></div></div></section>

      <section className="bg-white py-20 md:py-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-[.7fr_1.3fr]"><Reveal><Intro eyebrow="FAQ" title="Human demonstration data" accent="questions" body="Practical answers for robotics teams scoping collection, formats and operator capacity."/></Reveal><Reveal><Accordion type="single" collapsible className="divide-y divide-slate-200 border-y border-slate-200">{faqs.map(({question,answer},i)=><AccordionItem key={question} value={`faq-${i}`} className="border-0"><AccordionTrigger className="py-6 text-left font-heading text-base font-bold text-[#15183f] hover:text-primary hover:no-underline md:text-lg">{question}</AccordionTrigger><AccordionContent className="pb-6 pr-8 leading-7 text-slate-600">{answer}</AccordionContent></AccordionItem>)}</Accordion></Reveal></div></section>

      <section className="relative overflow-hidden bg-[#0d1b30] py-24 text-white md:py-32"><div className="absolute inset-0 opacity-25 [background-image:radial-gradient(circle_at_20%_30%,#20d3b0_0,transparent_28%),radial-gradient(circle_at_80%_70%,#ff9d13_0,transparent_22%)]"/><div className="container relative mx-auto max-w-5xl px-4 text-center"><Reveal><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-300">Pilot before scale</p><h2 className="mt-5 font-heading text-4xl font-bold md:text-6xl">Start with a pilot, <span className="text-teal-300">not a purchase order.</span></h2><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-white/68">Tell us your embodiment, tasks and training framework. We will return with a task design, diversity split, failure protocol and a four-week pilot that proves the format loads.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link to={CONTACT}><Button size="lg" className="h-13 px-7">Scope a Collection Programme <ArrowRight className="ml-2 h-4 w-4"/></Button></Link><Link to="/contact-us" className="inline-flex h-13 items-center justify-center rounded-lg border border-white/20 px-7 font-semibold text-white hover:bg-white/10">Talk to our robotics data team</Link></div></Reveal></div></section>
    </main>
  </AIDataServicesLayout>;
};

export default HumanDemonstrationsPage;
