import { Link } from "react-router-dom";
import {
  ArrowRight, BadgeCheck, BookOpenCheck, Boxes, Building2, CheckCircle2,
  ClipboardCheck, FileCheck2, FileKey2, FileScan, Files, Fingerprint,
  GraduationCap, Hand, HeartPulse, Languages, Landmark, LayoutTemplate,
  LibraryBig, ListTree, LockKeyhole, PackageCheck, PenLine, ReceiptText,
  ScanText, ShieldCheck, Table2, Tags, Waypoints,
} from "lucide-react";
import SectionHeader from "../../shared/SectionHeader";
import { useScrollReveal } from "@/hooks/use-scroll-reveal";

const Reveal = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => {
  const { ref, isVisible } = useScrollReveal();
  return <div ref={ref} className={`reveal-up ${isVisible ? "visible" : ""} ${className}`}>{children}</div>;
};

const annotationTypes = [
  [LayoutTemplate, "Document Layout & Region Annotation", "Headers, footers, columns, tables, figures, captions and marginalia mapped as structural zones.", "Layout-aware models · document parsing"],
  [Waypoints, "Key-Value Pair Extraction", "Field labels linked to the correct values across changing templates and positions.", "Invoices · forms · statements"],
  [Table2, "Table Structure Recognition", "Rows, columns, headers, merged cells, spanning cells and borderless tables represented structurally.", "Financial · logistics · laboratory data"],
  [ReceiptText, "Line-Item Extraction", "Repeating records parsed with multi-line items, taxes, totals and continuation pages handled correctly.", "Invoices · claims · purchase orders"],
  [ClipboardCheck, "Form Fields & Checkboxes", "Text inputs, checkbox states, radio groups, signatures, dates, ticks and hand-drawn crosses.", "Applications · onboarding · surveys"],
  [PenLine, "Handwriting Transcription", "Line- or word-level transcription with explicit confidence flags for ambiguous strokes.", "Filled forms · archives · clinical notes"],
  [Fingerprint, "Signature, Stamp & Seal Detection", "Presence, position and type of signatures, initials, official stamps, seals and watermarks.", "KYC · contracts · trade paperwork"],
  [Files, "Classification & Multi-Page Splitting", "Document classes identified and scanned batches separated at the correct boundaries.", "Mailrooms · claims · records migration"],
  [ListTree, "Reading Order Annotation", "Human reading sequence recorded across columns, sidebars, footnotes, wraps and inserts.", "Document understanding · accessibility"],
  [Tags, "Entities in Document Context", "Parties, dates, amounts, policy numbers, clause references and domain values tied to page context.", "Contracts · claims · compliance"],
  [FileKey2, "PII & Redaction Marking", "Sensitive fields located, classified and prepared for masking or safe downstream handling.", "Privacy · safe datasets · sharing"],
  [ScanText, "OCR Ground-Truth Transcription", "Character-accurate reference data for degraded scans, unusual typefaces and non-Latin scripts.", "OCR training · benchmarking · archives"],
] as const;

const documentTypes = [
  [ReceiptText, "Financial", "Invoices, receipts, purchase orders, statements, reports and tax forms"],
  [Fingerprint, "Identity & KYC", "Passports, ID cards, driving licences, utility bills and address proofs"],
  [ShieldCheck, "Insurance", "Claim forms, policy documents, loss reports and assessment records"],
  [Landmark, "Legal", "Contracts, agreements, court filings, notarised documents and certificates"],
  [PackageCheck, "Logistics & Trade", "Bills of lading, packing lists, declarations, dockets and manifests"],
  [HeartPulse, "Healthcare", "Patient forms, lab reports, prescriptions, discharge summaries and notes"],
  [GraduationCap, "HR & Education", "Applications, certificates, transcripts, mark sheets and attendance records"],
  [LibraryBig, "Archival", "Historical registers, manuscripts, microfilm scans and property records"],
] as const;

const process = [
  ["01", "Sample & schema review", "Assess templates, scan quality, language mix and target fields."],
  ["02", "Guideline authoring", "Define fields, normalisation rules and every ambiguous case."],
  ["03", "Template mapping", "Plan coverage across every distinct layout before production."],
  ["04", "Team calibration", "Qualify annotators against expert field-level ground truth."],
  ["05", "Pilot batch", "Confirm schema, field accuracy and acceptance thresholds."],
  ["06", "Production + QA", "Track accuracy per field so weak signals cannot hide in averages."],
  ["07", "Delivery & iteration", "Ship data, field reports and versioned correction rounds."],
] as const;

const quality = [
  ["Per-field", "Accuracy", "Every schema field is scored and reported separately."],
  ["CER / WER", "Transcription", "Character and word error rates against expert reference."],
  ["Cell-level", "Tables", "Merged and spanning cells tracked independently."],
  ["Gold sets", "Drift control", "Hidden expert documents detect production drift."],
  ["Double entry", "Critical fields", "Amounts and identifiers independently compared."],
  ["Coverage", "Templates", "Every layout variant represented and audited."],
] as const;

const hardParts = [
  [Table2, "Tables Without Borders", "Alignment and whitespace imply structure to people, but not models. We explicitly rule merged headers, wrapped rows, nested tables and continuation pages."],
  [Hand, "Handwriting & Mixed Content", "Ambiguous strokes, corrections and overflow receive confidence rules. Illegible content is flagged—not confidently guessed."],
  [BookOpenCheck, "Reading Order", "Columns, sidebars, footnotes and wrapped text are sequenced as a human reads them, preserving semantic meaning."],
  [Files, "Document Boundaries", "Cover pages, page-number restarts and type changes determine where one file ends and the next begins."],
] as const;

const industries = [
  [Landmark, "Banking & Fintech", "KYC onboarding, statements, loan files and cheques"],
  [ShieldCheck, "Insurance", "Claims intake, policies, assessments and medical bills"],
  [PackageCheck, "Logistics & Trade", "Bills of lading, customs and proof of delivery"],
  [ReceiptText, "Accounting & AP", "Invoices, receipts, expense processing and reconciliation"],
  [HeartPulse, "Healthcare", "Patient forms, lab reports and records digitisation"],
  [Building2, "Legal & Government", "Contracts, filings, applications and public records"],
  [GraduationCap, "Education", "Transcripts, mark sheets, certificates and admissions"],
  [LibraryBig, "Archives", "Registers, manuscripts and degraded historical scans"],
] as const;

const expertiseLinks = [
  ["Digital Conversion", "/digital-conversion", "Scanned-to-structured pipelines at volume"],
  ["Image Processing", "/image-processing", "Deskew, despeckle, contrast and scan-quality handling"],
  ["Metadata Services", "/metadata-services", "Structured extraction and controlled tagging"],
  ["Editorial & Publishing", "/editorial-publishing-designing-services", "Page anatomy, hierarchy and reading order"],
] as const;

export const DocumentDefinition = () => <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.82fr_1.18fr] lg:gap-20"><SectionHeader label="Beyond OCR" title="What Is Document &" gradientText="OCR Annotation?" centered={false}/><div className="space-y-5 text-base leading-8 text-muted-foreground"><p>Document annotation teaches a model to read a page the way a person does—not only recognising characters, but understanding that one string is the invoice total, a block is the shipping address, rows form a table and a new document begins here.</p><p>Modern document AI combines text, layout and visual features. Its training data must therefore capture <strong className="text-foreground">what the text says, where it sits and how it relates</strong> to everything around it.</p><div className="grid overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-2"><article className="bg-card p-5"><h3 className="font-heading font-bold text-foreground">OCR vs document annotation</h3><p className="mt-2 text-sm leading-6">OCR turns pixels into characters. Annotation adds field relationships, table structure, reading order and page meaning.</p></article><article className="bg-card p-5"><h3 className="font-heading font-bold text-foreground">Document vs text annotation</h3><p className="mt-2 text-sm leading-6">If position changes the label, it belongs here. Clean digital strings whose layout is irrelevant belong to the future Text & NLP Annotation service.</p></article></div></div></Reveal></div></section>;

const DocumentTypesVisual = () => <div className="grid min-h-[520px] gap-px overflow-hidden rounded-[2rem] border border-[#d6e2df] bg-[#d6e2df] shadow-[0_24px_80px_rgba(15,35,45,.10)] lg:grid-cols-4">
  <article className="relative bg-white p-6"><span className="font-mono text-[10px] font-bold uppercase tracking-[.14em] text-[#087e68]">01 · Layout regions</span><div className="mt-7 aspect-[.72] rounded-lg border border-[#ccd8d5] bg-[#fbfcfc] p-4"><div className="h-4 w-2/5 rounded bg-[#18324a]/18"/><div className="mt-5 grid grid-cols-2 gap-3"><div className="space-y-2">{[80,95,70,88,56].map((w,i)=><div key={i} className="h-2 rounded bg-[#18324a]/12" style={{width:`${w}%`}}/>)}</div><div className="space-y-2">{[90,62,84,50].map((w,i)=><div key={i} className="h-2 rounded bg-[#18324a]/12" style={{width:`${w}%`}}/>)}</div></div><div className="absolute left-10 right-10 top-[42%] h-[31%] rounded border-2 border-[#0aa487] bg-[#0aa487]/8"><span className="absolute -top-5 left-0 text-[9px] font-bold text-[#087e68]">TABLE</span></div><div className="absolute bottom-9 left-10 right-10 h-9 rounded border border-amber-400 bg-amber-100/50"/></div></article>
  <article className="bg-white p-6"><span className="font-mono text-[10px] font-bold uppercase tracking-[.14em] text-[#087e68]">02 · Key-value links</span><div className="relative mt-8 space-y-7">{[0,1,2,3,4].map(i=><div key={i} className="grid grid-cols-[1fr_28px_1fr] items-center gap-2"><div className="h-8 rounded border border-[#dce5e3] bg-[#f5f8f7] p-2"><div className="h-2 w-3/4 rounded bg-[#18324a]/18"/></div><svg viewBox="0 0 28 10" className="overflow-visible"><path d="M0 5 C8 0 20 10 28 5" fill="none" stroke={i===2?"#e59b19":"#0aa487"} strokeWidth="1.5" strokeDasharray="2 2"/></svg><div className={`h-8 rounded border p-2 ${i===2?"border-amber-300 bg-amber-50":"border-[#7dd8c7] bg-[#eaf9f5]"}`}><div className="h-2 w-2/3 rounded bg-[#18324a]/18"/></div></div>)}</div></article>
  <article className="bg-white p-6"><span className="font-mono text-[10px] font-bold uppercase tracking-[.14em] text-[#087e68]">03 · Table structure</span><div className="mt-10 overflow-hidden rounded-lg border-2 border-[#0aa487] bg-[#f8fbfa]"><div className="grid grid-cols-3 border-b border-[#0aa487]"><div className="col-span-2 h-10 border-r border-[#0aa487] bg-[#dff5ef] p-3"><div className="h-2 w-2/3 rounded bg-[#087e68]/30"/></div><div className="h-10 p-3"><div className="h-2 rounded bg-[#18324a]/15"/></div></div>{[0,1,2,3].map(r=><div key={r} className="grid grid-cols-3 border-b border-[#99cfc4] last:border-0">{[0,1,2].map(c=><div key={c} className="h-12 border-r border-[#99cfc4] p-3 last:border-0"><div className="h-2 rounded bg-[#18324a]/15"/><div className="mt-2 h-1.5 w-2/3 rounded bg-[#18324a]/10"/></div>)}</div>)}</div><p className="mt-5 text-xs leading-5 text-[#657181]">Merged header · borderless inference · row and column boundaries</p></article>
  <article className="bg-white p-6"><span className="font-mono text-[10px] font-bold uppercase tracking-[.14em] text-[#087e68]">04 · Handwriting</span><div className="mt-8 rounded-xl border border-[#dce5e3] bg-[#fbfcfc] p-4">{["Signature","Date","Reference","Amount"].map((x,i)=><div key={x} className="mb-5 last:mb-0"><div className="flex justify-between text-[9px] uppercase tracking-wider text-[#7b8792]"><span>{x}</span><span className={i===2?"text-amber-600":"text-[#087e68]"}>{i===2?"Review":"Transcribed"}</span></div><div className={`mt-1.5 flex h-10 items-center rounded border px-3 ${i===2?"border-amber-300 bg-amber-50":"border-[#8bdccc] bg-[#eefaf7]"}`}><span className="font-serif text-lg italic text-[#24364a]/65">{i===0?"A. sample":i===1?"12 / 08":i===2?"unclear":"1 2 4 —"}</span></div></div>)}</div></article>
</div>;

export const DocumentAnnotationTypes = () => <section className="relative overflow-hidden bg-[#f4f8f7] py-20 md:py-24"><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-primary/40 to-transparent"/><div className="container mx-auto px-4"><SectionHeader label="Position + Structure" title="Document Annotation Types" gradientText="We Deliver" subtitle="From page anatomy to character-level reference data, every label preserves the relationships a document model needs."/><Reveal className="mx-auto mt-12 max-w-7xl"><DocumentTypesVisual/></Reveal><div className="mx-auto mt-12 grid max-w-7xl gap-4 md:grid-cols-2 xl:grid-cols-4">{annotationTypes.map(([Icon,title,text,best],i)=><article key={title} className="group rounded-2xl border border-[#d9e5e2] bg-white p-6 shadow-[0_12px_35px_rgba(15,35,45,.05)] transition-all duration-300 hover:-translate-y-1 hover:border-primary/35"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#e4f8f3] text-[#087e68]"><Icon className="h-5 w-5"/></span><span className="font-mono text-xs font-bold text-[#087e68]">{String(i+1).padStart(2,"0")}</span></div><h3 className="mt-5 font-heading text-lg font-bold text-[#142238]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#596679]">{text}</p><p className="mt-5 border-t border-[#e2ebe8] pt-4 text-[10px] font-bold uppercase leading-4 tracking-[.08em] text-[#087e68]">Best for: {best}</p></article>)}</div></div></section>;

export const DocumentCoverage = () => <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Real-World Coverage" title="Document Types We" gradientText="Work With" subtitle="Template diversity is planned across operational documents, regulated records and publishing-grade archives."/><Reveal className="mx-auto grid max-w-7xl overflow-hidden rounded-[2rem] border border-border md:grid-cols-2 lg:grid-cols-4">{documentTypes.map(([Icon,title,text],i)=><article key={title} className="group border-b border-r border-border bg-card p-7 transition-colors hover:bg-primary/[.045]"><div className="flex items-center justify-between"><Icon className="h-5 w-5 text-primary"/><span className="font-mono text-xs text-muted-foreground">0{i+1}</span></div><h3 className="mt-7 font-heading text-lg font-bold text-foreground">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</Reveal></div></section>;

export const PublishingExpertise = () => <section className="relative overflow-hidden bg-[#142238] py-20 text-white md:py-28"><div className="absolute inset-0 opacity-[.06]" style={{backgroundImage:"linear-gradient(#35dfbb 1px,transparent 1px),linear-gradient(90deg,#35dfbb 1px,transparent 1px)",backgroundSize:"56px 56px"}}/><div className="container relative mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><Reveal><span className="font-mono text-xs font-bold uppercase tracking-[.18em] text-[#59e8c9]">The eQOURSE difference</span><h2 className="mt-5 font-heading text-4xl font-bold leading-tight md:text-5xl">Document structure is already <span className="text-[#35dfbb]">our core business.</span></h2><p className="mt-6 max-w-xl text-lg leading-8 text-white/72">Generic annotation vendors see a scan as an image with text. Our publishing, prepress and conversion teams see page anatomy: hierarchy, columns, reading order, table structure and continuation logic.</p><p className="mt-5 max-w-xl leading-7 text-white/65">Document AI training data is that established discipline expressed as annotations—not a capability added after the fact.</p></Reveal><div className="grid gap-px overflow-hidden rounded-[2rem] border border-white/15 bg-white/15 sm:grid-cols-2">{expertiseLinks.map(([title,href,text])=><Link key={title} to={href} className="group bg-[#182a40] p-7 transition-colors hover:bg-[#1d354c]"><span className="flex items-center justify-between font-heading text-lg font-bold"><span>{title}</span><ArrowRight className="h-4 w-4 text-[#59e8c9] transition-transform group-hover:translate-x-1"/></span><p className="mt-3 text-sm leading-6 text-white/65">{text}</p></Link>)}</div></div></div></section>;

export const DocumentProcess = () => <section className="bg-white py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Versioned Workflow" title="Our Document Annotation" gradientText="Process" subtitle="New templates and fields loop back into the schema—so production stays controlled as the corpus evolves."/><Reveal className="relative mx-auto mt-14 max-w-7xl"><svg viewBox="0 0 1200 105" className="absolute left-0 top-7 hidden h-28 w-full lg:block" aria-hidden="true"><defs><marker id="doc-arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="#0aa487"/></marker></defs><path d="M65 30 H1125" stroke="#bcd8d2" strokeWidth="2" strokeDasharray="5 7"/><path d="M1125 35 C1125 96 1050 94 1010 94 H250 C165 94 125 76 125 50" fill="none" stroke="#0aa487" strokeWidth="2" strokeDasharray="6 6" markerEnd="url(#doc-arrow)"/></svg><ol className="relative grid gap-4 sm:grid-cols-2 lg:grid-cols-7">{process.map(([n,title,text],i)=><li key={n} className="group relative rounded-2xl border border-[#dce7e4] bg-[#f7faf9] p-5 transition-all hover:-translate-y-1 hover:border-primary/35"><span className="relative z-10 grid h-12 w-12 place-items-center rounded-xl bg-gradient-to-br from-[#087e68] to-[#18b99a] font-mono text-sm font-bold text-white shadow-lg shadow-primary/15">{n}</span><h3 className="mt-6 font-heading font-bold leading-5 text-[#142238]">{title}</h3><p className="mt-3 text-xs leading-5 text-[#657181]">{text}</p>{i===6&&<span className="mt-4 block text-[9px] font-bold uppercase tracking-wider text-[#087e68]">Feeds the next schema version</span>}</li>)}</ol></Reveal></div></section>;

export const DocumentQuality = () => <section className="bg-[#eef5f3] py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><Reveal><SectionHeader label="Field-Level QA" title="One Average Cannot Hide the" gradientText="Field That Matters" centered={false}/><p className="-mt-8 max-w-xl leading-7 text-muted-foreground">A dataset can be 97% accurate overall and still fail when the total or policy number is wrong. We expose quality at the field, cell, template and document-type level.</p><div className="mt-9 grid grid-cols-2 gap-3 sm:grid-cols-3">{quality.map(([value,label,text])=><article key={label} className="rounded-xl border border-[#d6e4e0] bg-white p-4"><strong className="font-heading text-lg text-[#087e68]">{value}</strong><span className="mt-1 block text-xs font-bold text-[#142238]">{label}</span><p className="mt-2 text-[11px] leading-4 text-[#657181]">{text}</p></article>)}</div></Reveal><Reveal className="relative"><picture><source srcSet="/assets/ai-data/annotation-labeling/document-ocr-annotation/document-annotation-field-accuracy-review.avif" type="image/avif"/><img src="/assets/ai-data/annotation-labeling/document-ocr-annotation/document-annotation-field-accuracy-review.webp" alt="Reviewer checking per-field extraction accuracy against a synthetic scanned document with a field-level score panel" width="1000" height="600" loading="lazy" decoding="async" className="w-full rounded-[2rem] border border-white object-cover shadow-[0_24px_70px_rgba(15,35,45,.16)]"/></picture><div className="absolute -bottom-5 left-5 right-5 flex items-center gap-3 rounded-xl border border-white/70 bg-white/90 p-4 shadow-xl backdrop-blur md:left-auto md:w-[300px]"><BadgeCheck className="h-8 w-8 text-primary"/><div><strong className="block text-sm text-foreground">Field-level evidence</strong><span className="text-xs text-muted-foreground">Not one misleading average</span></div></div></Reveal></div></div></section>;

export const DocumentChallenges = () => <section className="bg-[linear-gradient(135deg,#17243a,#232043)] py-20 text-white md:py-24"><div className="container mx-auto px-4"><SectionHeader dark label="Edge-Case Protocol" title="Tables, Handwriting and the Problems" gradientText="That Break Document Pipelines" subtitle="Each hard case receives a documented ruling before production—and every ruling is versioned for the full team."/><div className="mx-auto mt-12 grid max-w-7xl gap-4 md:grid-cols-2">{hardParts.map(([Icon,title,text],i)=><Reveal key={title}><article className="group h-full rounded-2xl border border-white/15 bg-white/[.065] p-7 transition-all hover:border-[#35dfbb]/40 hover:bg-white/[.09]"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#35dfbb]/12 text-[#59e8c9]"><Icon className="h-5 w-5"/></span><span className="font-mono text-xs text-[#59e8c9]">0{i+1}</span></div><h3 className="mt-6 font-heading text-xl font-bold text-white">{title}</h3><p className="mt-3 leading-7 text-white/72">{text}</p></article></Reveal>)}</div></div></section>;

export const DocumentSecurity = () => <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><SectionHeader label="Sensitive by Nature" title="Handling Sensitive" gradientText="Documents" centered={false}/><p className="-mt-8 leading-7 text-muted-foreground">Invoices contain commercial terms, KYC carries identity data and claims may include medical history. We treat document annotation as a compliance workflow from scoping onward.</p><div className="mt-8 rounded-2xl border border-primary/20 bg-primary/5 p-5"><LockKeyhole className="h-6 w-6 text-primary"/><p className="mt-3 text-sm leading-6 text-foreground/75">Regulatory obligations vary by jurisdiction and sector. Controls are agreed during scoping—not retrofitted after data begins moving.</p></div></div><Reveal className="grid gap-px overflow-hidden rounded-[2rem] border border-border bg-border sm:grid-cols-2">{[
  ["PII classification","Names, addresses, identifiers, financial and health fields"],
  ["Redaction & masking","Sensitive values removed before downstream use"],
  ["Pseudonymisation","Relationships preserved using consistent surrogate values"],
  ["Restricted environments","Client perimeter or VPN workflows where required"],
  ["Named, vetted teams","Identified annotators operating under NDA"],
  ["Audit, retention & deletion","Access trails and contract-defined disposal"],
].map(([title,text])=><article key={title} className="bg-card p-6"><CheckCircle2 className="h-5 w-5 text-primary"/><h3 className="mt-4 font-heading font-bold text-foreground">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</Reveal></div></div></section>;

export const DeliveryAndCommercial = () => <>
  <section className="bg-[#f4f8f7] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Model-Ready Delivery" title="Formats, Industries and" gradientText="Operational Fit"/><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[.8fr_1.2fr]"><Reveal className="rounded-[2rem] bg-[#142238] p-8 text-white md:p-10"><span className="font-mono text-xs uppercase tracking-wider text-[#59e8c9]">Output formats</span><div className="mt-6 flex flex-wrap gap-2">{["JSON / JSONL","hOCR","ALTO XML","PAGE XML","FUNSD","DocVQA","CoNLL + coordinates","COCO regions","CSV / TSV","Excel","Searchable PDF","Custom schema"].map(x=><span key={x} className="rounded-full border border-white/15 bg-white/5 px-3 py-2 text-xs text-white/78">{x}</span>)}</div><p className="mt-8 border-t border-white/15 pt-6 text-sm leading-6 text-white/65">Every delivery includes a manifest, per-field and per-document-type QA report, template coverage summary and versioned schema.</p></Reveal><div className="grid gap-3 sm:grid-cols-2">{industries.map(([Icon,title,text])=><article key={title} className="flex gap-4 rounded-2xl border border-[#d9e5e2] bg-white p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#e4f8f3] text-[#087e68]"><Icon className="h-5 w-5"/></span><div><h3 className="font-heading font-bold text-[#142238]">{title}</h3><p className="mt-1 text-xs leading-5 text-[#657181]">{text}</p></div></article>)}</div></div></div></section>
  <section className="bg-white py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-2"><Reveal><SectionHeader label="Human-Controlled Acceleration" title="OCR-Assisted Annotation—Faster Without" gradientText="Compounding Errors" centered={false}/><div className="-mt-8 space-y-4 leading-7 text-muted-foreground"><p>On clean, printed documents, annotators can correct and structure OCR output instead of starting from zero. We measure the resulting field accuracy exactly as we measure manual work.</p><p>When pre-fill creates anchoring errors—degraded scans, dense tables, handwriting or non-Latin scripts—we shift that class or field back to manual transcription.</p><p className="font-semibold text-foreground">OCR pre-fill is never used for OCR ground-truth datasets; the reference must remain independent.</p></div></Reveal><Reveal><h2 className="font-heading text-3xl font-bold text-foreground">What Determines Document Annotation Cost?</h2><p className="mt-4 leading-7 text-muted-foreground">Projects are scoped per page, document or field. The pilot turns these variables into an evidence-based throughput estimate.</p><div className="mt-7 grid grid-cols-2 gap-x-6 gap-y-4">{["Fields per document","Table complexity","Template variety","Scan quality","Handwriting","Language & script","Accuracy tier","Domain expertise","Security tier","Programme volume"].map((x,i)=><div key={x} className="flex items-center gap-3 border-b border-border pb-3 text-sm font-medium text-foreground"><span className="font-mono text-[10px] text-primary">{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div><Link to="/free-pilot" className="mt-8 inline-flex items-center gap-2 font-semibold text-primary hover:underline">Share 20–50 representative documents <ArrowRight className="h-4 w-4"/></Link></Reveal></div></div></section>
</>;

export const RelatedAndWhy = () => <section className="bg-[#eef5f3] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="One Connected Data Practice" title="Related Services and" gradientText="Proof"/><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[1.15fr_.85fr]"><Reveal className="grid gap-3 sm:grid-cols-2">{[
  ["Image Annotation","/ai-data-services/annotation-labeling/image-annotation","Spatial labels for visual models"],
  ["Digital Conversion","/digital-conversion","Scanned-to-structured content pipelines"],
  ["Image Processing","/image-processing","Scan preparation and quality handling"],
  ["Metadata Services","/metadata-services","Controlled extraction and tagging"],
  ["Data Cleaning & Validation","/ai-data-services/cleaning-validation","Dataset consistency and validation"],
  ["All Annotation Services","/ai-data-services/annotation-labeling","Explore the complete annotation practice"],
].map(([title,href,text])=><Link key={title} to={href} className="group rounded-2xl border border-[#d7e4e0] bg-white p-5"><div className="flex items-center justify-between"><h3 className="font-heading font-bold text-[#142238]">{title}</h3><ArrowRight className="h-4 w-4 text-primary transition-transform group-hover:translate-x-1"/></div><p className="mt-2 text-xs leading-5 text-[#657181]">{text}</p></Link>)}</Reveal><Reveal className="rounded-[2rem] bg-[#142238] p-8 text-white"><h2 className="font-heading text-2xl font-bold">Why eQOURSE for document annotation</h2><ul className="mt-6 space-y-4">{["Publishing-grade page-structure expertise","Per-field accuracy reporting","Double-entry on critical values","Template coverage planned upfront","30+ languages including Indic scripts","Compliance-ready, ISO-certified processes"].map(x=><li key={x} className="flex gap-3 text-sm text-white/76"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#59e8c9]"/>{x}</li>)}</ul><div className="mt-8 grid grid-cols-3 gap-2 border-t border-white/15 pt-6 text-center">{[["Samples","/ai-data-samples"],["Case studies","/casestudy"],["Testimonials","/clients-testimonials"]].map(([x,href])=><Link key={x} to={href} className="rounded-lg bg-white/5 p-3 text-xs font-semibold hover:bg-white/10">{x}</Link>)}</div></Reveal></div></div></section>;
