import { Link } from "react-router-dom";
import { ArrowRight, BadgeCheck, Box, CheckCircle2, Crosshair, FileJson2, Gauge, Layers3, LockKeyhole, Map, Radar, Route, ScanLine, ShieldCheck, Waypoints } from "lucide-react";
import SectionHeader from "../../shared/SectionHeader";
import { useScrollReveal } from "@/hooks/use-scroll-reveal";

const Reveal = ({children,className=""}:{children:React.ReactNode;className?:string}) => { const {ref,isVisible}=useScrollReveal(); return <div ref={ref} className={`min-w-0 reveal-up ${isVisible?"visible":""} ${className}`}>{children}</div>; };

const types = [
  [Box,"3D Cuboid Annotation","Oriented boxes with position, dimensions, heading, class and motion attributes.","Detection · AV perception"],
  [ScanLine,"Point-Level Semantic Segmentation","Every return classified as road, vehicle, pedestrian, vegetation, pole or another defined class.","Scene understanding · HD maps"],
  [Layers3,"3D Instance Segmentation","Point masks separated by object so adjacent instances remain individually addressable.","Dense scenes · manipulation"],
  [Waypoints,"Multi-Sweep Tracking (4D)","Persistent IDs across consecutive sweeps for motion, velocity and trajectory learning.","Forecasting · tracking"],
  [Crosshair,"Camera–LiDAR Sensor Fusion","Cuboids projected into camera views and checked for cross-sensor agreement.","Fusion models · calibration"],
  [Radar,"Radar & Multi-Sensor Fusion","Radar returns associated with LiDAR and camera detections, including velocity attributes.","ADAS · all-weather sensing"],
  [Route,"Lane, Road & Drivable Space","Elevation-aware lanes, road edges, stop lines, free space and navigable regions.","Planning · HD mapping"],
  [Map,"Ground, Pose & Occupancy","Surface classes, 3D keypoints, voxel occupancy and aerial or survey structures.","Robotics · spatial AI"],
];

const process = [
  ["01","Sensor review","Validate calibration, density and scene complexity."],
  ["02","Schema","Fix frames, axes, units, headings and edge-case rules."],
  ["03","Qualification","Score spatial reasoning against expert geometry."],
  ["04","Pilot","Confirm thresholds and error by component."],
  ["05","Production","Track geometry and sequence consistency."],
  ["06","3D review","Automated checks plus second-pass and projection QA."],
  ["07","Delivery","Ship format, QA report and versioned iterations."],
];

const PointCloudMini = () => <svg viewBox="0 0 720 280" className="h-auto w-full" role="img" aria-labelledby="point-cloud-title"><title id="point-cloud-title">Sparse LiDAR scan rings with oriented three-dimensional cuboids</title><defs><pattern id="dots3d" width="22" height="14" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1.2" fill="#5be6c5" opacity=".55"/></pattern></defs><rect width="720" height="280" rx="28" fill="#0c1829"/><path d="M35 242 Q360 38 685 242M62 247 Q360 76 658 247M95 252 Q360 112 625 252M132 258 Q360 148 588 258" fill="none" stroke="#47bea9" strokeWidth="1" strokeDasharray="2 7" opacity=".6"/><path d="M0 0h720v280H0z" fill="url(#dots3d)" opacity=".38"/><g fill="none" stroke="#5be6c5" strokeWidth="2"><path d="M166 153l82-20 49 25-83 22zM166 153v58l48 28 83-24v-57M214 180v59"/><path d="M416 106l64-15 39 20-65 18zM416 106v45l38 22 65-18v-44M454 129v44"/></g><g fill="none" stroke="#f0ad4e" strokeWidth="2"><path d="M315 173l76-18 45 22-77 22zM315 173v51l44 25 77-21v-51M359 199v50"/></g><path d="M72 233h576" stroke="#5be6c5" strokeDasharray="3 10" opacity=".4"/><circle cx="360" cy="255" r="5" fill="#f0ad4e" className="motion-safe:animate-pulse"/></svg>;

export const LidarDefinition = () => <section className="bg-white py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><Reveal><SectionHeader label="Geometry Into Meaning" title="What Is 3D Point Cloud &" gradientText="LiDAR Annotation?" centered={false}/><div className="-mt-8 space-y-4 leading-7 text-muted-foreground"><p>A LiDAR sweep contains hundreds of thousands of position and intensity returns. Annotation turns those sparse points into objects, surfaces, drivable regions and persistent tracks a perception model can learn.</p><p>A point cloud has geometry but little visual context. Spatial reasoning, coordinate conventions and camera reference matter more here than texture or appearance.</p></div><div className="mt-8 rounded-2xl border border-border p-6"><h3 className="font-heading text-xl font-bold">3D cuboid vs. 2D bounding box</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">A 2D box locates an appearance in an image. A 3D cuboid describes actual x, y and z position, length, width, height and yaw—where the object is, its physical extent and which way it faces.</p><div className="mt-5 flex gap-3"><Link to="/ai-data-services/annotation-labeling/image-annotation" className="text-sm font-semibold text-primary hover:underline">Image Annotation</Link><Link to="/ai-data-services/annotation-labeling/video-annotation" className="text-sm font-semibold text-primary hover:underline">Video Annotation</Link></div></div></Reveal><Reveal><PointCloudMini/></Reveal></div></div></section>;

export const LidarTypes = () => <section className="bg-[#f2f7f7] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Spatial Labels" title="3D Annotation Types" gradientText="We Deliver" subtitle="Each layer answers a different perception question: object, surface, motion, fusion or occupancy."/><Reveal className="mx-auto mt-12 max-w-6xl overflow-hidden rounded-[2rem] border border-[#18364a]"><picture><source srcSet="/assets/ai-data/annotation-labeling/3d-point-cloud-lidar-annotation/3d-annotation-types-cuboid-segmentation-fusion.avif" type="image/avif"/><img src="/assets/ai-data/annotation-labeling/3d-point-cloud-lidar-annotation/3d-annotation-types-cuboid-segmentation-fusion.webp" alt="Examples of 3D cuboid annotation, point-level semantic segmentation, multi-sweep tracking and camera-LiDAR fusion" width="1200" height="800" loading="lazy" decoding="async" className="w-full"/></picture></Reveal><div className="mx-auto mt-10 grid max-w-7xl gap-px overflow-hidden rounded-3xl border border-[#d5e1df] bg-[#d5e1df] md:grid-cols-2 xl:grid-cols-4">{types.map(([Icon,title,text,best],i)=><article key={title as string} className="group bg-white p-6 transition hover:bg-[#f8fbfa]"><div className="flex justify-between"><Icon className="h-5 w-5 text-[#098a74]"/><span className="font-mono text-[10px] text-[#098a74]">{String(i+1).padStart(2,"0")}</span></div><h3 className="mt-5 font-heading font-bold text-[#142238]">{title as string}</h3><p className="mt-2 text-sm leading-6 text-[#5f6c79]">{text as string}</p><p className="mt-4 border-t border-[#e2e9e7] pt-3 text-[10px] font-bold uppercase tracking-wider text-[#087e68]">Best for: {best as string}</p></article>)}</div></div></section>;

export const CalibrationTruth = () => <section className="relative overflow-hidden bg-[#0c1829] py-20 text-white md:py-28"><div className="absolute inset-0 opacity-30"><PointCloudMini/></div><div className="container relative mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><Reveal><span className="font-mono text-xs font-bold uppercase tracking-[.2em] text-[#5be6c5]">The trust layer</span><h2 className="mt-5 font-heading text-4xl font-bold leading-tight md:text-5xl">Fusion is a calibration problem <span className="text-[#5be6c5]">before annotation begins.</span></h2><p className="mt-6 leading-7 text-white/72">A correct cuboid projected through incorrect extrinsics looks wrong in the camera view. Fudging the box to match the image only corrupts the geometry. We validate the sensor relationship first.</p><p className="mt-5 border-l-2 border-[#f0ad4e] pl-4 font-semibold text-[#ffd28c]">Annotation cannot repair bad calibration; it can only bake the error into training data.</p></Reveal><Reveal className="rounded-[2rem] border border-white/12 bg-white/[.06] p-7 backdrop-blur"><div className="space-y-5">{[["Extrinsic calibration","Project sample cuboids across sensors before production."],["Temporal synchronisation","Check timestamp offsets for moving objects."],["Ego-motion compensation","Verify multi-sweep aggregation and motion correction."],["Intrinsic distortion","Inspect projection near camera-frame edges."],["Long-capture drift","Re-check alignment across extended sessions."],["Fusion agreement","Separate systematic calibration error from scattered label error."]].map(([t,d],i)=><div key={t} className="grid grid-cols-[36px_1fr] gap-4 border-b border-white/10 pb-4 last:border-0"><span className={`grid h-8 w-8 place-items-center rounded-full font-mono text-[10px] font-bold ${i===0?"bg-[#f0ad4e] text-[#142238]":"bg-[#5be6c5]/12 text-[#5be6c5]"}`}>0{i+1}</span><div><h3 className="font-heading font-bold">{t}</h3><p className="mt-1 text-sm leading-6 text-white/62">{d}</p></div></div>)}</div></Reveal></div></div></section>;

export const LidarProcess = () => <section className="bg-white py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Calibration First" title="Our 3D Annotation" gradientText="Process" subtitle="Geometry, coordinate conventions and acceptance thresholds are fixed before production scales."/><Reveal className="mx-auto mt-12 max-w-7xl"><svg viewBox="0 0 1200 155" className="hidden w-full md:block" role="img" aria-labelledby="lidar-process-title"><title id="lidar-process-title">Seven-step eQOURSE 3D annotation process from sensor review and calibration validation through to delivery</title><defs><marker id="processArrow3d" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0l6 3-6 3z" fill="#0b9b82"/></marker></defs><path d="M90 58H1110" stroke="#bddbd4" strokeWidth="2" strokeDasharray="5 8"/><path d="M1110 95C1110 145 235 145 235 102" fill="none" stroke="#f0ad4e" strokeWidth="2" strokeDasharray="5 7" markerEnd="url(#processArrow3d)"/>{process.map(([n,t],i)=><g key={n} transform={`translate(${70+i*170} 28)`}><circle cx="35" cy="30" r="28" fill={i===0?"#f0ad4e":"#0b9b82"}/><text x="35" y="35" textAnchor="middle" fill={i===0?"#142238":"white"} fontSize="12" fontWeight="700">{n}</text><text x="35" y="88" textAnchor="middle" fill="#142238" fontSize="12" fontWeight="700">{t}</text></g>)}</svg><div className="grid gap-3 md:hidden">{process.map(([n,t,d],i)=><article key={n} className="grid grid-cols-[46px_1fr] gap-4 rounded-2xl border border-[#dbe6e3] p-4"><span className={`grid h-11 w-11 place-items-center rounded-full font-mono text-xs font-bold ${i===0?"bg-[#f0ad4e] text-[#142238]":"bg-[#0b9b82] text-white"}`}>{n}</span><div><h3 className="font-heading font-bold">{t}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{d}</p></div></article>)}</div><div className="mt-8 hidden grid-cols-7 gap-3 md:grid">{process.map(([n,,d])=><p key={n} className="text-center text-xs leading-5 text-muted-foreground">{d}</p>)}</div></Reveal></div></section>;

export const GeometricQuality = () => <section className="bg-[#edf6f3] py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><Reveal><SectionHeader label="Measure Every Component" title="How We Measure 3D" gradientText="Annotation Quality" centered={false}/><p className="-mt-8 leading-7 text-muted-foreground">A single IoU score hides the cause of a bad cuboid. We separate translation, dimensions and heading, then report sequence, fusion and distance-band performance.</p><div className="mt-8 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-[#d4e5df] bg-[#d4e5df]">{[["3D IoU","Expert ground truth"],["Translation","Centre offset in metres"],["Dimensions","Length · width · height"],["Heading","Yaw error in degrees"],["Tracks","ID switches · fragments"],["Fusion","Projection agreement"],["Point inclusion","Object geometry checks"],["Range bands","Near vs. sparse far field"]].map(([v,l])=><div key={v} className="bg-white p-4"><strong className="font-heading text-lg text-[#087e68]">{v}</strong><span className="mt-1 block text-xs text-[#596879]">{l}</span></div>)}</div></Reveal><Reveal className="relative"><picture><source srcSet="/assets/ai-data/annotation-labeling/3d-point-cloud-lidar-annotation/3d-annotation-geometric-accuracy-review.avif" type="image/avif"/><img src="/assets/ai-data/annotation-labeling/3d-point-cloud-lidar-annotation/3d-annotation-geometric-accuracy-review.webp" alt="Reviewer comparing an annotated 3D cuboid against expert ground truth with translation, dimension and heading error displayed" width="1000" height="600" loading="lazy" decoding="async" className="w-full rounded-[2rem] border border-white object-cover shadow-[0_24px_70px_rgba(17,31,50,.16)]"/></picture><div className="absolute -bottom-5 left-5 flex items-center gap-3 rounded-xl border border-white/70 bg-white/92 p-4 shadow-xl backdrop-blur"><BadgeCheck className="h-8 w-8 text-primary"/><div><strong className="block text-sm">Heading scored separately</strong><span className="text-xs text-muted-foreground">A reversed cuboid cannot hide in IoU</span></div></div></Reveal></div></div></section>;

export const SensorLimits = () => <section className="bg-[#1f2345] py-20 text-white md:py-28"><div className="container mx-auto px-4"><SectionHeader label="Physical Limits" title="What the Sensor Can—and" gradientText="Cannot—Tell You" subtitle="Where returns cannot support a reliable label, the dataset should say so." light/><div className="mx-auto grid max-w-7xl gap-px overflow-hidden rounded-[2rem] border border-white/15 bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{[["Sparsity at distance","Minimum point thresholds by class; flag or exclude below them."],["Total occlusion","No returns means no evidence—extent follows a documented convention."],["Reflective surfaces","Glass, metal and dark paint create missing or misleading returns."],["Weather artefacts","Rain, fog, snow and dust require explicit noise rulings."],["Ground ambiguity","Slopes, kerbs and uneven terrain affect every resting cuboid."],["Heading ambiguity","Symmetric sparse objects need camera reference or a fixed convention."],["Sensor patterns","32-beam and 128-beam density require different guidance."],["Honest uncertainty","Incomplete evidence is flagged rather than replaced by invented dimensions."]].map(([t,d],i)=><article key={t} className="bg-[#1f2345] p-6 transition hover:bg-[#292e55]"><span className="font-mono text-[10px] text-[#63e3c7]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-5 font-heading font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-white/68">{d}</p></article>)}</div></div></section>;

export const FormatsApplications = () => <><section className="bg-white py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[.85fr_1.15fr]"><Reveal className="rounded-[2rem] bg-[#102237] p-8 text-white"><FileJson2 className="h-7 w-7 text-[#5be6c5]"/><h2 className="mt-5 font-heading text-3xl font-bold">Output formats and coordinate fidelity</h2><p className="mt-4 text-sm leading-6 text-white/68">We confirm coordinate frame, handedness, axis orientation, units and heading convention in the pilot.</p><div className="mt-6 flex flex-wrap gap-2">{["PCD","LAS / LAZ","PLY","KITTI BIN","ROS bag","E57","KITTI labels","nuScenes JSON","Waymo-style","SUSTechPOINTS","JSON / JSONL","CSV cuboids","Custom schema"].map(x=><span key={x} className="rounded-full border border-white/15 bg-white/5 px-3 py-2 text-xs text-white/78">{x}</span>)}</div><p className="mt-7 border-t border-white/15 pt-5 text-sm text-white/65">Delivered with manifest, QA report, track metrics, fusion agreement, range-band accuracy and versioned guidelines.</p></Reveal><Reveal><SectionHeader label="Deployment Context" title="Where 3D Annotation" gradientText="Is Used" centered={false}/><div className="-mt-7 grid gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-2">{[["Autonomous vehicles & ADAS","Objects · tracks · lanes · fusion"],["Robotics & warehouses","Obstacles · free space · grasp points"],["Drones & aerial survey","Terrain · structures · utilities"],["Construction & mining","Progress · equipment · haul roads"],["Agriculture","Crop structure · terrain · navigation"],["Smart cities & rail","Assets · clearance · traffic geometry"]].map(([t,d])=><div key={t} className="bg-card p-5"><h3 className="font-heading font-bold">{t}</h3><p className="mt-2 text-sm text-muted-foreground">{d}</p></div>)}</div><Link to="/robotics-training-data-services" className="mt-6 inline-flex items-center gap-2 font-semibold text-primary">Robotics Training Data Services <ArrowRight className="h-4 w-4"/></Link></Reveal></div></div></section></>;

export const AssistedSecurityCost = () => <><section className="bg-[#f4f8f7] py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><Reveal><SectionHeader label="Controlled Acceleration" title="Model-Assisted 3D" gradientText="Annotation" centered={false}/><div className="-mt-8 space-y-4 leading-7 text-muted-foreground"><p>Usable detectors can pre-generate common near-field cuboids for human correction, reducing placement time in dense scenes.</p><p>The hidden risk is missed far-field and rare objects. Recall therefore must be measured by distance band against manually annotated controls.</p><p className="font-semibold text-foreground">Far-field, rare classes and benchmark datasets remain manual where pre-generation would bias the result.</p></div></Reveal><Reveal className="rounded-[2rem] border border-[#d6e4df] bg-white p-8"><LockKeyhole className="h-7 w-7 text-primary"/><h2 className="mt-5 font-heading text-2xl font-bold">Sensor data security</h2><ul className="mt-6 grid gap-3 text-sm text-foreground/75">{["ISO 9001 and ISO 27001 processes","Named, vetted pools under NDA","Role-based sequence access","Face and plate redaction where required","Restricted or client-controlled environments","Audit trails, retention and deletion"].map(x=><li key={x} className="flex gap-3"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{x}</li>)}</ul></Reveal></div></div></section><section className="bg-[#102237] py-20 text-white md:py-28"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.75fr_1.25fr] lg:items-center"><Reveal><span className="font-mono text-xs font-bold uppercase tracking-[.18em] text-[#5be6c5]">Quote the hard frames</span><h2 className="mt-5 font-heading text-4xl font-bold leading-tight md:text-5xl">What determines <span className="text-[#5be6c5]">3D annotation cost?</span></h2><p className="mt-6 leading-7 text-white/70">3D is priced per sweep. Share 20–50 representative frames plus calibration files for a scoped estimate.</p></Reveal><Reveal className="grid gap-px overflow-hidden rounded-3xl border border-white/15 bg-white/10 sm:grid-cols-2">{["Annotation type","Objects per sweep","Point density","Sequence tracking","Sensor fusion","Classes + attributes","Accuracy thresholds","Scene difficulty","Sampling rate","Security + turnaround"].map((x,i)=><div key={x} className="bg-[#102237] p-5 text-sm text-white/76"><span className="mr-3 font-mono text-[10px] text-[#5be6c5]">{String(i+1).padStart(2,"0")}</span>{x}</div>)}</Reveal></div></div></section></>;

const related=[["Image Annotation","/ai-data-services/annotation-labeling/image-annotation"],["Video Annotation","/ai-data-services/annotation-labeling/video-annotation"],["Robotics Training Data","/robotics-training-data-services"],["AI Data Collection","/ai-data-services/data-collection"],["Data Cleaning & Validation","/ai-data-services/cleaning-validation"],["Computer Vision Model Testing","/ai-data-services/model-testing/computer-vision-model-testing"],["All Annotation Services","/ai-data-services/annotation-labeling"]];
export const LidarRelated = () => <section className="bg-[#edf5f2] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Connected Perception Practice" title="Related Services and" gradientText="Proof"/><p className="mx-auto mb-8 max-w-4xl text-center text-sm leading-7 text-muted-foreground">Producing labelled point clouds to train a model is this page. Measuring how a trained model performs on real deployment conditions is <Link to="/ai-data-services/model-testing/computer-vision-model-testing" className="font-semibold text-primary hover:underline">computer vision model testing</Link>—one produces a dataset, the other produces a report.</p><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[1.15fr_.85fr]"><Reveal className="grid gap-3 sm:grid-cols-2">{related.map(([t,h])=><Link key={t} to={h} className="group flex items-center justify-between rounded-2xl border border-[#d6e4df] bg-white p-5"><h3 className="font-heading font-bold text-[#142238]">{t}</h3><ArrowRight className="h-4 w-4 text-primary transition group-hover:translate-x-1"/></Link>)}</Reveal><Reveal className="rounded-[2rem] bg-[#142238] p-8 text-white"><Gauge className="h-7 w-7 text-[#5be6c5]"/><h2 className="mt-5 font-heading text-2xl font-bold">Why eQOURSE for 3D annotation</h2><ul className="mt-6 space-y-4">{["Calibration validated before annotation","Translation, dimension and heading reported separately","Accuracy broken out by distance band","Sensor limits documented honestly","Full data pipeline under one provider","ISO-certified processes","Pilot on your hardest frames"].map(x=><li key={x} className="flex gap-3 text-sm text-white/76"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#5be6c5]"/>{x}</li>)}</ul><div className="mt-8 grid grid-cols-3 gap-2 border-t border-white/15 pt-6">{[["Samples","/ai-data-samples/computer-vision"],["Cases","/casestudy"],["Reviews","/clients-testimonials"]].map(([x,h])=><Link key={x} to={h} className="rounded-lg bg-white/5 p-3 text-center text-xs font-semibold hover:bg-white/10">{x}</Link>)}</div></Reveal></div></div></section>;
