import { Link } from "react-router-dom";
import {
  ArrowRight,
  BadgeCheck,
  Building2,
  CalendarClock,
  CircleDollarSign,
  FileCheck2,
  Landmark,
  Languages,
  Scale,
  ShieldCheck,
  Stethoscope,
} from "lucide-react";
import SectionHeader from "../../shared/SectionHeader";
import { useScrollReveal } from "@/hooks/use-scroll-reveal";
import { verificationFaqs, verificationProcess, verificationTypes } from "./DataValidationVerificationContent";

const Reveal = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => {
  const { ref, isVisible } = useScrollReveal();
  return <div ref={ref} className={`reveal-up ${isVisible ? "visible" : ""} ${className}`}>{children}</div>;
};

export const VerificationMotionStyles = () => <style>{`
  @keyframes verify-flow{to{stroke-dashoffset:-48}}
  @keyframes verify-resolve{0%,18%{transform:scaleX(.08);opacity:.25}55%,100%{transform:scaleX(1);opacity:1}}
  @keyframes verify-pulse{0%,100%{transform:scale(.92);opacity:.58}50%{transform:scale(1);opacity:1}}
  .verify-flow{animation:verify-flow 4.4s linear infinite}.verify-resolve{transform-origin:left;animation:verify-resolve 4.8s ease-in-out infinite alternate}.verify-pulse{transform-origin:center;animation:verify-pulse 3.2s ease-in-out infinite}
  @media(prefers-reduced-motion:reduce){.verify-flow,.verify-resolve,.verify-pulse{animation:none!important}}
`}</style>;

export const VerificationTrustStrip = () => (
  <section aria-label="Verification service assurances" className="border-y border-border bg-white">
    <div className="container mx-auto grid grid-cols-2 gap-px bg-border px-4 md:grid-cols-4">
      {[["Source agreed first","Authority, limits and currency"],["Six clear states","Not a misleading yes or no"],["Conflict preserved","Disagreement becomes evidence"],["30+ languages","Global reach + Indian depth"]].map(([a,b])=><div key={a} className="bg-white px-4 py-5 text-center"><strong className="text-sm">{a}</strong><p className="mt-1 text-xs text-muted-foreground">{b}</p></div>)}
    </div>
  </section>
);

export const QuestionsAndSourceTruth = () => (
  <>
    <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Scope before tools" title="Three Different Questions About" gradientText="the Same Record" subtitle="Cleaning, validation and verification are connected—but they buy three different answers."/>
      <Reveal className="mx-auto mt-12 max-w-6xl overflow-x-auto rounded-[2rem] border border-border bg-white shadow-soft"><table className="w-full min-w-[780px] text-left"><thead className="bg-[#eef6f4] text-sm"><tr><th className="px-6 py-5">Layer</th><th className="px-6 py-5">Question</th><th className="px-6 py-5">What a pass means</th><th className="px-6 py-5">What it cannot catch</th></tr></thead><tbody>{[["Cleaning","Is it well-formed?","Correct type, format, encoding and no unwanted duplicates","A valid-looking address that belongs to nobody"],["Validation","Is it internally plausible?","Real date, permitted range, required fields and schema conformance","A plausible date that is not the actual date"],["Verification","Is it actually true?","Confirmed against an agreed authoritative source","Nothing beyond the limits of the source and method"]].map((r,i)=><tr key={r[0]} className={`border-t border-border ${i===2?"bg-primary/[.055]":""}`}>{r.map((v,j)=><td key={v} className={`px-6 py-5 text-sm leading-6 ${j===0?"font-heading text-base font-bold":j===1?"font-semibold":"text-muted-foreground"}`}>{v}</td>)}</tr>)}</tbody></table></Reveal>
      <Reveal className="mx-auto mt-7 flex max-w-6xl flex-wrap gap-4 text-sm"><Link to="/ai-data-services/cleaning-validation/data-cleaning-preparation" className="inline-flex items-center gap-2 font-bold text-primary hover:underline">Data Cleaning &amp; Preparation <ArrowRight className="h-4 w-4"/></Link><Link to="/ai-data-services/cleaning-validation/dataset-qa-label-audit" className="inline-flex items-center gap-2 font-bold text-primary hover:underline">Dataset QA &amp; Label Audit <ArrowRight className="h-4 w-4"/></Link></Reveal>
    </div></section>
    <section className="overflow-hidden bg-[radial-gradient(circle_at_74%_18%,hsl(171_49%_19%),transparent_33%),linear-gradient(135deg,hsl(225_47%_12%),hsl(225_42%_17%))] py-20 text-white md:py-28"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.86fr_1.14fr]"><div><span className="font-mono text-xs font-bold uppercase tracking-[.2em] text-teal-300">The question before the first check</span><h2 className="mt-6 font-heading text-4xl font-bold leading-tight md:text-6xl">Verified Against <span className="text-teal-300">What?</span></h2><p className="mt-6 text-lg leading-8 text-white/70">“Verify this data” is not an instruction until the authoritative source, its limits and its permitted use are agreed for every field.</p><p className="mt-6 border-l-2 border-amber-300 pl-5 text-sm font-semibold leading-7 text-white/90">Where no source of truth exists, verification is impossible. The honest deliverable is plausibility review—not confident-looking output with no evidence behind it.</p></div><div className="rounded-[2rem] border border-white/10 bg-white/[.045] p-7 md:p-9"><svg viewBox="0 0 620 330" role="img" aria-labelledby="sourceTruthTitle" className="w-full"><title id="sourceTruthTitle">Different record fields connecting to different authoritative sources</title><rect x="34" y="45" width="190" height="238" rx="24" fill="#fff" fillOpacity=".08" stroke="#fff" strokeOpacity=".18"/>{[0,1,2,3].map(i=><g key={i}><circle cx="70" cy={88+i*50} r="9" fill={i===3?"#f2b84b":"#4fd1b4"}/><rect x="93" y={80+i*50} width={76+i*15} height="15" rx="7" fill="#fff" fillOpacity=".5"/><path className="verify-flow" d={`M224 ${88+i*50} C310 ${88+i*50},315 ${64+i*70},382 ${64+i*70}`} fill="none" stroke={i===3?"#f2b84b":"#4fd1b4"} strokeWidth="3" strokeDasharray="8 8"/></g>)}{[0,1,2,3].map(i=><g key={i}><rect x="382" y={38+i*70} width="190" height="52" rx="18" fill="#fff" fillOpacity=".09" stroke="#fff" strokeOpacity=".18"/><circle className={i===1?"verify-pulse":""} cx="416" cy={64+i*70} r="11" fill={i===3?"#f2b84b":"#4fd1b4"}/><rect x="441" y={57+i*70} width={70+i*13} height="14" rx="7" fill="#fff" fillOpacity=".48"/></g>)}</svg><div className="grid gap-px overflow-hidden rounded-2xl bg-white/10 sm:grid-cols-2">{[["Authority","Why this source decides the field"],["Currency","How recently it was updated"],["Coverage","Which markets or entities are absent"],["Access","Licence, terms and rate limits"]].map(([a,b])=><div key={a} className="bg-[#111b2e] p-5"><strong className="text-sm text-white">{a}</strong><p className="mt-2 text-xs leading-5 text-white/55">{b}</p></div>)}</div></div></Reveal></div></section>
  </>
);

export const VerificationCapabilities = () => (
  <section className="bg-[#f2f7f5] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="External reality, field by field" title="What We" gradientText="Verify" subtitle="The source and evidence change with the claim. The reporting discipline does not."/>
    <Reveal className="mx-auto mt-12 max-w-6xl overflow-hidden rounded-[2rem] border border-border bg-white shadow-soft"><img src="/assets/ai-data/cleaning-validation/data-validation-verification/data-verification-sources-conflict-status.webp" alt="Examples of source matching, multi-source cross-referencing, source conflict and verification status values" width="1200" height="800" loading="lazy" decoding="async" className="w-full"/></Reveal>
    <div className="mx-auto mt-8 grid max-w-6xl gap-px overflow-hidden rounded-[2rem] border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{verificationTypes.map(([a,b],i)=><Reveal key={a} className="h-full"><article className="group h-full bg-card p-6 transition-colors hover:bg-primary/[.05]"><span className="font-mono text-[10px] font-bold text-primary">{String(i+1).padStart(2,"0")}</span><h3 className="mt-5 font-heading text-lg font-bold">{a}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{b}</p></article></Reveal>)}</div>
    <Reveal className="mx-auto mt-8 flex max-w-6xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><Link to="/ai-data-services/annotation-labeling/document-ocr-annotation" className="inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline">Need the source documents extracted first? Explore Document &amp; OCR Annotation <ArrowRight className="h-4 w-4"/></Link><Link to="/robotics-training-data-services/multimodal-sensor-data" className="inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline">For sensor and robotics datasets, see Multimodal Sensor Data <ArrowRight className="h-4 w-4"/></Link></Reveal>
  </div></section>
);

const conflictReasons = ["Timing","Definition","Scope","Jurisdiction","Granularity","Genuine error","Legitimate multiplicity"];

export const ConflictConsequenceDecay = () => (
  <>
    <section className="bg-background py-20 md:py-28"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.82fr_1.18fr]"><div><span className="font-mono text-xs font-bold uppercase tracking-[.2em] text-amber-700">Conflict is a result</span><h2 className="mt-5 font-heading text-4xl font-bold leading-tight md:text-5xl">Two Authoritative Sources. <span className="text-primary">Two Answers.</span></h2><p className="mt-6 leading-8 text-muted-foreground">We do not quietly choose the first result. The hierarchy is agreed before production, the disagreement is preserved, and a senior reviewer adjudicates what the protocol cannot settle.</p><p className="mt-6 border-l-2 border-amber-500 pl-5 font-semibold leading-7">A project reporting zero conflicts has probably checked only one source.</p></div><div className="rounded-[2rem] border border-border bg-[#f7faf9] p-7"><div className="flex flex-wrap gap-2">{conflictReasons.map(x=><span key={x} className="rounded-full border border-border bg-white px-4 py-2 text-xs font-semibold">{x}</span>)}</div><div className="mt-8 grid gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-2">{[["01","Hierarchy first","Decide which source wins per field and why."],["02","Record disagreement","The conflict remains visible in the dataset."],["03","Senior adjudication","Escalate only what the hierarchy cannot resolve."],["04","Report by field","High-conflict fields expose deeper source problems."]].map(([n,a,b])=><div key={n} className="bg-white p-5"><span className="font-mono text-[10px] text-amber-700">{n}</span><h3 className="mt-3 font-heading font-bold">{a}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{b}</p></div>)}</div></div></Reveal></div></section>
    <section className="bg-[#eef5f3] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Spend judgement where error matters" title="Triage by Consequence," gradientText="Not Convenience" subtitle="Verification is expensive because external truth must be checked. The right scope follows downstream risk."/><Reveal className="mx-auto mt-12 max-w-6xl overflow-x-auto rounded-[2rem] border border-border bg-white"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-[#153e3b] text-white"><tr><th className="px-6 py-5">Verify thoroughly</th><th className="px-6 py-5">Verify by sample</th><th className="px-6 py-5">Leave to cleaning &amp; validation</th></tr></thead><tbody><tr className="align-top"><td className="px-6 py-6"><ul className="space-y-3">{["Decision-triggering values","Regulated or reported figures","Anything wrong could harm","Join identifiers"].map(x=><li key={x}>• {x}</li>)}</ul></td><td className="border-x border-border px-6 py-6"><ul className="space-y-3">{["Analytical attributes","Segmentation fields","Non-critical contacts","Historical records"].map(x=><li key={x}>• {x}</li>)}</ul></td><td className="px-6 py-6"><ul className="space-y-3">{["Cosmetic fields","Free-text notes","Fields with no consumer","Upstream-validated values"].map(x=><li key={x}>• {x}</li>)}</ul></td></tr></tbody></table></Reveal><Reveal className="mx-auto mt-7 max-w-6xl rounded-2xl border border-primary/20 bg-primary/[.055] p-6"><strong>Sampling answers a rate, not a record.</strong><p className="mt-2 text-sm leading-7 text-muted-foreground">A statistically designed sample can estimate dataset accuracy. It cannot guarantee that one specific high-consequence record is correct.</p></Reveal></div></section>
    <section className="overflow-hidden bg-[linear-gradient(135deg,hsl(225_46%_14%),hsl(253_41%_18%))] py-20 text-white md:py-28"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.78fr_1.22fr]"><div><CalendarClock className="h-9 w-9 text-teal-300"/><h2 className="mt-6 font-heading text-4xl font-bold leading-tight md:text-5xl">Verification Has a <span className="text-teal-300">Shelf Life</span></h2><p className="mt-6 leading-8 text-white/65">A verified record is a dated evidence claim. Contact details, roles, addresses, registrations and licences change at different speeds, so refresh cadence belongs at field level.</p><p className="mt-6 text-sm font-semibold leading-7 text-amber-200">Directional patterns are not promised rates. We measure decay on your data.</p></div><div className="overflow-hidden rounded-[2rem] border border-white/10"><table className="w-full text-left text-sm"><thead className="bg-white/[.08]"><tr><th className="px-6 py-5">Field type</th><th className="px-6 py-5">Directional decay</th></tr></thead><tbody>{[["Direct phone and email","Fastest"],["Job title and role","Fast"],["Operating status and address","Moderate"],["Registration details","Slow"],["Certifications and licences","Step-change at expiry"],["Historical facts","Stable, but records can be revised"]].map(([a,b],i)=><tr key={a} className="border-t border-white/10"><td className="px-6 py-4 text-white/72">{a}</td><td className="px-6 py-4 font-bold text-teal-200">{b}<div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="verify-resolve h-full rounded-full bg-gradient-to-r from-teal-400 to-amber-300" style={{width:`${92-i*11}%`,animationDelay:`${i*.18}s`}}/></div></td></tr>)}</tbody></table></div></Reveal></div></section>
  </>
);

export const ProcessAndDelivery = () => (
  <>
    <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Evidence before scale" title="How a Verification" gradientText="Engagement Runs" subtitle="Consequence and source authority are decided first; adjudication continuously improves the protocol."/>
      <Reveal className="mx-auto mt-12 max-w-7xl"><div className="relative hidden h-28 lg:block" aria-hidden="true"><svg viewBox="0 0 1200 108" className="h-full w-full" preserveAspectRatio="none"><path className="verify-flow" d="M55 38H1140C1170 38 1170 88 1138 88H460C430 88 430 64 460 64H640" fill="none" stroke="hsl(var(--primary))" strokeOpacity=".5" strokeWidth="2" strokeDasharray="8 8"/></svg><div className="absolute inset-x-0 top-3 grid grid-cols-7 gap-3">{verificationProcess.map(([n],i)=><div key={n} className="flex justify-center"><span className={`grid h-12 w-12 place-items-center rounded-full border-2 font-mono text-xs font-bold ${i<2?"border-primary bg-primary text-primary-foreground shadow-soft":"border-primary bg-background text-primary"}`}>{n}</span></div>)}</div></div><ol className="grid gap-px overflow-hidden rounded-[2rem] border border-border bg-border sm:grid-cols-2 lg:grid-cols-7">{verificationProcess.map(([n,t,d],i)=><li key={n} className={`bg-card p-5 ${i<2?"lg:border-t-4 lg:border-primary":""}`}><span className="font-mono text-xs font-bold text-primary lg:hidden">{n}</span><h3 className="mt-5 font-heading text-sm font-bold lg:mt-1">{t}</h3><p className="mt-3 text-xs leading-relaxed text-muted-foreground">{d}</p></li>)}</ol></Reveal>
    </div></section>
    <section className="bg-[#f2f7f5] py-20 md:py-28"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><span className="font-mono text-xs font-bold uppercase tracking-[.2em] text-primary">Every field carries evidence</span><h2 className="mt-5 font-heading text-4xl font-bold leading-tight md:text-5xl">What You Get <span className="text-primary">Back</span></h2><p className="mt-6 leading-8 text-muted-foreground">A value alone hides uncertainty. Delivery separates confirmed, conflicted, contradicted, unresolved and deliberately unattempted fields—with the source and date attached.</p><div className="mt-7 grid gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-2">{[["Verified","Confirmed against the agreed source"],["Verified with conflict","Confirmed, but another source disagreed"],["Contradicted","The source returns a different value"],["Unverifiable","No available source could settle it"],["Not attempted","Deliberately outside the agreed scope"],["Plausibility only","Reviewed as reasonable, not verified"]].map(([a,b],i)=><div key={a} className="bg-white p-4"><div className="flex items-center gap-3"><span className={`h-2.5 w-2.5 rounded-full ${i===0?"bg-primary":i===1?"bg-amber-500":i===2?"bg-red-500":"bg-slate-400"}`}/><strong className="text-sm">{a}</strong></div><p className="mt-2 pl-5 text-xs leading-5 text-muted-foreground">{b}</p></div>)}</div></div><div className="overflow-hidden rounded-[2rem] border border-border bg-white shadow-soft"><img src="/assets/ai-data/cleaning-validation/data-validation-verification/verification-status-conflict-report.webp" alt="Reviewer examining a verification report showing per-field verification rate, conflict register and unverifiable items" width="1000" height="600" loading="lazy" decoding="async" className="w-full"/><div className="grid gap-px bg-border sm:grid-cols-2"><div className="bg-white p-5"><strong className="text-sm">Conflict register</strong><p className="mt-1 text-xs text-muted-foreground">Sources, values and adjudication retained.</p></div><div className="bg-white p-5"><strong className="text-sm">Refresh guidance</strong><p className="mt-1 text-xs text-muted-foreground">Re-verification cadence by field type.</p></div></div></div></Reveal></div></section>
  </>
);

export const ExpertiseLanguageSecurity = () => {
  const domains = [[Stethoscope,"Medical & life sciences","Clinical claims, terminology and safety statements"],[Scale,"Legal & regulatory","Citations, applicability and regulatory status"],[Landmark,"Finance","Figures, structures, registrations and disclosures"],[Building2,"Technical & engineering","Specifications, standards and compatibility"],[FileCheck2,"Education & scientific","Alignment, equivalence, published figures and methods"]] as const;
  return <>
    <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Qualification is part of the method" title="Some Facts Need a" gradientText="Qualified Reviewer" subtitle="External truth is domain-specific. The reviewer must understand both the claim and the source."/><div className="mx-auto mt-12 grid max-w-6xl gap-px overflow-hidden rounded-[2rem] border border-border bg-border sm:grid-cols-2 lg:grid-cols-5">{domains.map(([Icon,a,b])=><article key={a} className="bg-card p-6"><Icon className="h-6 w-6 text-primary"/><h3 className="mt-5 font-heading font-bold">{a}</h3><p className="mt-3 text-xs leading-6 text-muted-foreground">{b}</p></article>)}</div><Reveal className="mx-auto mt-7 max-w-6xl"><Link to="/smes" className="inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline">Meet our Subject Matter Experts <ArrowRight className="h-4 w-4"/></Link></Reveal></div></section>
    <section className="bg-[#eef5f3] py-20 md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-2"><div><Languages className="h-8 w-8 text-primary"/><h2 className="mt-6 font-heading text-3xl font-bold md:text-4xl">Verification Across Languages and Markets</h2><p className="mt-5 leading-8 text-muted-foreground">Native-speaker verification across 30+ global languages, with comprehensive Indian regional-language depth and regional-source knowledge across India, South-East Asia and global markets.</p><div className="mt-6 grid gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-2">{["Native-language source reading","Transliteration matching","Local naming and address logic","CIN, GSTIN, PAN, UEN and equivalents"].map(x=><div key={x} className="bg-white p-4 text-sm font-semibold">{x}</div>)}</div></div><div><ShieldCheck className="h-8 w-8 text-primary"/><h2 className="mt-6 font-heading text-3xl font-bold md:text-4xl">Security, Lawful Access and Auditability</h2><p className="mt-5 leading-8 text-muted-foreground">ISO 9001 and ISO 27001 certified processes, named reviewers, role-based access, restricted environments, contracted retention and a trace of what was checked, against what, by whom and when.</p><p className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-7 text-amber-950">We work within source licensing and terms of use and flag sources that cannot lawfully be used. Verification involving personal data has its own lawful-basis considerations; confirm them with counsel.</p><Link to="/ai-data-services/cleaning-validation/pii-detection-redaction" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline">PII Detection &amp; Redaction <ArrowRight className="h-4 w-4"/></Link></div></Reveal></div></section>
  </>;
};

export const CommercialRelatedProofFAQ = () => {
  const related = [["Data Cleaning & Preparation","/ai-data-services/cleaning-validation/data-cleaning-preparation"],["Dataset QA & Label Audit","/ai-data-services/cleaning-validation/dataset-qa-label-audit"],["LLM Training Data Curation","/ai-data-services/cleaning-validation/llm-data-curation"],["PII Detection & Redaction","/ai-data-services/cleaning-validation/pii-detection-redaction"],["Metadata Enrichment","/ai-data-services/cleaning-validation/metadata-enrichment"],["Document & OCR Annotation","/ai-data-services/annotation-labeling/document-ocr-annotation"],["All Cleaning & Validation Services","/ai-data-services/cleaning-validation"]] as const;
  return <>
    <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><Reveal className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.72fr_1.28fr]"><div><CircleDollarSign className="h-9 w-9 text-primary"/><h2 className="mt-6 font-heading text-3xl font-bold md:text-4xl">What Determines Verification Cost?</h2><p className="mt-5 leading-8 text-muted-foreground">Start with a representative sample. Its real verification, conflict and unverifiable rates make the production estimate meaningful.</p></div><div className="grid gap-x-10 sm:grid-cols-2">{["Fields verified per record","Source accessibility","Distinct source count","Cross-reference depth","Conflict and adjudication rate","Domain expertise","Language and jurisdiction","Sample versus census","Correction versus flagging","Security tier and turnaround"].map(x=><div key={x} className="flex gap-3 border-b border-border py-4 text-sm font-medium"><BadgeCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{x}</div>)}</div></Reveal></div></section>
    <section className="bg-[linear-gradient(135deg,hsl(225_46%_13%),hsl(172_45%_13%))] py-20 text-white md:py-24"><div className="container mx-auto px-4"><SectionHeader light label="Connected evidence" title="Related Data Quality" gradientText="Services" subtitle="Move from structural integrity to source-backed truth without losing the audit trail."/><nav aria-label="Related Data Cleaning and Validation services" className="mx-auto mt-10 grid max-w-6xl gap-px overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{related.map(([a,h])=><Link key={a} to={h} className="group flex items-center justify-between bg-[#111b2d] p-6 text-sm font-semibold text-white/80 transition-colors hover:bg-white/[.08] hover:text-teal-200"><span>{a}</span><ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1"/></Link>)}</nav></div></section>
    <section className="bg-[#eef5f3] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Proof before promise" title="See the" gradientText="Work"/><div className="mx-auto mt-10 grid max-w-6xl gap-px overflow-hidden rounded-[2rem] border border-border bg-border md:grid-cols-3">{[["Cleaned dataset samples","/ai-data-samples/cleaned-datasets","Inspect production-style data structures."],["Case studies","/casestudy","See managed quality programmes in context."],["Client testimonials","/clients-testimonials","Evaluate delivery and partnership evidence."]].map(([a,h,b],i)=><Link key={a} to={h} className="group bg-white p-7 transition-colors hover:bg-primary/[.05]"><span className="font-mono text-xs text-primary">0{i+1}</span><h3 className="mt-7 font-heading text-xl font-bold">{a}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{b}</p><ArrowRight className="mt-7 h-5 w-5 text-primary transition-transform group-hover:translate-x-1"/></Link>)}</div></div></section>
    <section className="bg-background py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Questions answered" title="Data Verification" gradientText="FAQ"/><div className="mx-auto mt-10 max-w-4xl divide-y divide-border border-y border-border">{verificationFaqs.map(([q,a],i)=><details key={q} className="group py-1"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-5 font-heading font-bold"><span><span className="mr-4 font-mono text-xs text-primary">{String(i+1).padStart(2,"0")}</span>{q}</span><span className="text-2xl font-light text-primary transition-transform group-open:rotate-45">+</span></summary><p className="max-w-3xl pb-6 pl-10 text-sm leading-7 text-muted-foreground">{a}</p></details>)}</div></div></section>
  </>;
};
