import { Link } from "react-router-dom";
import { ArrowRight, BadgeCheck, BookOpen, Braces, CheckCircle2, FileJson2, Languages, Link2, ListChecks, LockKeyhole, MessageSquareText, Network, Search, ShieldCheck, Sparkles, Tags, Target, TextCursorInput, Users } from "lucide-react";
import SectionHeader from "../../shared/SectionHeader";
import { useScrollReveal } from "@/hooks/use-scroll-reveal";

const Reveal = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => {
  const { ref, isVisible } = useScrollReveal();
  return <div ref={ref} className={`min-w-0 reveal-up ${isVisible ? "visible" : ""} ${className}`}>{children}</div>;
};

const capabilities = [
  [Tags, "Named Entity Recognition", "People, organisations, products, locations and domain entities with precise offsets."],
  [Braces, "Nested & Overlapping Entities", "Multiple valid entity layers preserved without flattening the meaning."],
  [Network, "Relation Extraction", "Typed links between entities, events, attributes and references."],
  [Link2, "Coreference Resolution", "Pronouns and repeated mentions connected to the correct real-world entity."],
  [ListChecks, "Text Classification", "Document, sentence or passage labels using a controlled taxonomy."],
  [MessageSquareText, "Sentiment & Aspect Sentiment", "Separate opinions about product, service, price and experience."],
  [Target, "Intent & Slot Filling", "User goals paired with the entities required to complete the action."],
  [BookOpen, "POS & Syntax", "Tokens, morphology, dependency relations and linguistic structure."],
  [TextCursorInput, "Span Highlighting", "Evidence, claims, clauses, answers and extractive text boundaries."],
  [Search, "Search Relevance", "Query-result relevance, intent match and graded ranking judgements."],
  [Languages, "MT Post-Editing", "Accuracy, fluency, terminology, register and cultural-fit corrections."],
  [Sparkles, "Semantic & RAG Quality", "Similarity, paraphrases, summary quality and chunk usefulness."],
] as const;

const process = [
  ["01", "Corpus review", "Inspect language, domains, edge cases and class balance."],
  ["02", "Taxonomy stress-test", "Run the proposed labels against real, ambiguous examples."],
  ["03", "Guidelines", "Document boundaries, precedence rules and worked examples."],
  ["04", "Calibration", "Qualify native reviewers and measure initial agreement."],
  ["05", "Pilot", "Validate quality, throughput and delivery schema."],
  ["06", "Production + QA", "Monitor drift, blind duplicates, gold sets and distributions."],
  ["07", "Delivery + iteration", "Ship data and feed new edge cases back into the taxonomy."],
] as const;

const hardCases = [
  ["Determiners", "Does ‘the Ministry’ begin at ‘the’ or at ‘Ministry’?"],
  ["Nested spans", "A hospital name may also contain a city and organisation."],
  ["Discontinuous spans", "One semantic unit can be interrupted by unrelated words."],
  ["Pronouns", "The nearest noun is not always the correct referent."],
  ["Negation", "‘Not bad’ cannot be scored token by token."],
  ["Mixed sentiment", "One sentence can praise service and criticise price."],
  ["Slang & typos", "Meaning survives spelling noise, abbreviations and informal syntax."],
  ["Domain ambiguity", "‘Discharge’ means different things in medicine, law and physics."],
] as const;

const languages = ["Hindi", "Bengali", "Tamil", "Telugu", "Marathi", "Gujarati", "Kannada", "Malayalam", "Punjabi", "Odia", "Assamese", "Urdu"];

const related = [
  ["LLM & RLHF Annotation", "/ai-data-services/annotation-labeling/llm-rlhf-annotation", "Human evaluation of model responses and alignment data"],
  ["Document & OCR Annotation", "/ai-data-services/annotation-labeling/document-ocr-annotation", "Layout-aware labels where position carries meaning"],
  ["Text Data Collection", "/ai-data-services/data-collection/text-data-collection", "Source or create multilingual language datasets"],
  ["Translation Services", "/translation-services", "Translation and machine-translation post-editing"],
  ["Localization Services", "/localization-services", "Language, locale and cultural adaptation"],
  ["Data Cleaning & Validation", "/ai-data-services/cleaning-validation", "Normalize, deduplicate and validate datasets"],
  ["Content Moderation Services", "/ai-data-services/annotation-labeling/content-moderation", "Run ongoing multilingual policy enforcement and appeals"],
  ["All Annotation Services", "/ai-data-services/annotation-labeling", "Explore the full annotation practice"],
] as const;

const AnnotationVisual = () => <div className="overflow-hidden rounded-[2rem] border border-[#d9e3df] bg-white shadow-[0_24px_70px_rgba(20,34,56,.10)]">
  <div className="flex items-center justify-between border-b border-[#e4ebe8] px-6 py-4"><span className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#087e68]">Semantic annotation canvas</span><div className="flex gap-1.5">{[0,1,2].map(i=><span key={i} className="h-2 w-2 rounded-full bg-[#d7e2df]"/>)}</div></div>
  <div className="grid md:grid-cols-2">
    <article className="border-b border-r border-[#e4ebe8] p-6"><span className="text-[10px] font-bold uppercase tracking-wider text-[#718078]">Named entities</span><p className="mt-6 text-lg leading-10 text-[#203047]">Schedule a visit to <mark className="rounded bg-[#c9f2e8] px-2 text-[#075f51]">Riverview Clinic</mark> in <mark className="rounded bg-[#fff0c7] px-2 text-[#8a5a00]">Pune</mark>.</p><div className="mt-5 flex gap-2 text-[9px] font-bold uppercase"><span className="rounded bg-[#c9f2e8] px-2 py-1 text-[#075f51]">Organisation</span><span className="rounded bg-[#fff0c7] px-2 py-1 text-[#8a5a00]">Location</span></div></article>
    <article className="border-b border-[#e4ebe8] p-6"><span className="text-[10px] font-bold uppercase tracking-wider text-[#718078]">Nested entity</span><div className="mt-7 rounded-lg border-2 border-[#9b8bd7] p-3 text-center text-[#203047]"><span className="rounded bg-[#d9f3ed] px-2 py-1">Institute of <span className="rounded bg-[#fff0c7] px-2 py-1">Delhi</span> Studies</span></div><div className="mt-5 flex justify-center gap-2 text-[9px] font-bold uppercase"><span className="text-[#6652b2]">Organisation</span><span className="text-[#8a5a00]">Location inside</span></div></article>
    <article className="border-r border-[#e4ebe8] p-6"><span className="text-[10px] font-bold uppercase tracking-wider text-[#718078]">Relation</span><div className="relative mt-7 flex items-center justify-between gap-5"><span className="rounded-lg bg-[#d9f3ed] px-4 py-2 font-semibold text-[#075f51]">medicine</span><svg viewBox="0 0 120 38" className="h-10 flex-1" aria-hidden="true"><defs><marker id="rel-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0 0v6l7-3z" fill="#df921a"/></marker></defs><path d="M3 30 C35 -6 83 -6 116 30" fill="none" stroke="#df921a" strokeWidth="2" markerEnd="url(#rel-arrow)"/><text x="60" y="14" textAnchor="middle" fontSize="9" fill="#8a5a00">treats</text></svg><span className="rounded-lg bg-[#eee9ff] px-4 py-2 font-semibold text-[#6652b2]">condition</span></div></article>
    <article className="p-6"><span className="text-[10px] font-bold uppercase tracking-wider text-[#718078]">Aspect sentiment</span><p className="mt-5 text-[#203047]"><span className="border-b-2 border-[#0aa487]">Setup was effortless</span>, but <span className="border-b-2 border-[#df921a]">support was slow</span>.</p><div className="mt-5 flex gap-3 text-xs"><span className="text-[#087e68]">Setup ↑ positive</span><span className="text-[#a56b0e]">Support ↓ negative</span></div></article>
  </div>
</div>;

export const TextDefinition = () => <section className="bg-white py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><Reveal><SectionHeader label="Meaning, Made Measurable" title="What Is Text & NLP" gradientText="Annotation?" centered={false}/><div className="-mt-8 space-y-4 leading-7 text-muted-foreground"><p>Text annotation adds structured meaning to written language so models can learn entities, intent, sentiment, relationships, evidence and categories.</p><p>Language is ambiguous: the same phrase can change meaning by domain, context, register or what came before. Reliable training data therefore needs a clear taxonomy and measured human agreement—not only a large annotation team.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-2"><Link to="/ai-data-services/annotation-labeling/document-ocr-annotation" className="rounded-xl border border-border p-4 text-sm hover:border-primary/40"><strong className="block text-foreground">When position matters</strong><span className="mt-1 block text-muted-foreground">Use Document & OCR Annotation</span></Link><Link to="/ai-data-services/annotation-labeling/llm-rlhf-annotation" className="rounded-xl border border-border p-4 text-sm hover:border-primary/40"><strong className="block text-foreground">When judging model output</strong><span className="mt-1 block text-muted-foreground">Use LLM & RLHF Annotation</span></Link></div></Reveal><Reveal><AnnotationVisual/></Reveal></div></div></section>;

export const TextAnnotationTypes = () => <section className="bg-[#f5f8f7] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Language Signals" title="Text Annotation Types" gradientText="We Deliver" subtitle="Choose the label that answers your model’s question—then define it precisely enough that two trained people reach the same answer."/><Reveal className="mx-auto mt-12 max-w-6xl"><AnnotationVisual/></Reveal><div className="mx-auto mt-10 grid max-w-7xl gap-3 md:grid-cols-2 xl:grid-cols-4">{capabilities.map(([Icon,title,text],i)=><article key={title} className="rounded-2xl border border-[#d8e4e0] bg-white p-5 transition hover:-translate-y-1 hover:border-primary/35"><div className="flex items-center justify-between"><Icon className="h-5 w-5 text-primary"/><span className="font-mono text-[10px] text-[#087e68]">{String(i+1).padStart(2,"0")}</span></div><h3 className="mt-5 font-heading font-bold text-[#142238]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#5f6d7b]">{text}</p>{title==="MT Post-Editing"&&<p className="mt-3 text-xs"><Link className="font-semibold text-primary hover:underline" to="/translation-services">Translation</Link> · <Link className="font-semibold text-primary hover:underline" to="/localization-services">Localization</Link></p>}</article>)}</div></div></section>;

export const TaxonomySection = () => <section className="relative overflow-hidden bg-[#142238] py-20 text-white md:py-28"><div className="absolute inset-0 opacity-[.06]" style={{backgroundImage:"radial-gradient(#52e4c6 1px,transparent 1px)",backgroundSize:"24px 24px"}}/><div className="container relative mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><Reveal><span className="font-mono text-xs font-bold uppercase tracking-[.18em] text-[#59e8c9]">Taxonomy before throughput</span><h2 className="mt-5 font-heading text-4xl font-bold leading-tight md:text-5xl">The label set matters more than <span className="text-[#59e8c9]">the annotator count.</span></h2><p className="mt-6 text-lg leading-8 text-white/72">If trained reviewers cannot apply a category consistently, scaling it only manufactures disagreement. We stress-test your taxonomy against genuine corpus samples before production.</p></Reveal><Reveal className="grid gap-px overflow-hidden rounded-[2rem] border border-white/15 bg-white/15 sm:grid-cols-2">{[["Mutually exclusive","Can one example validly fit two labels?"],["Exhaustive","Where do valid edge cases go?"],["Learnable","Can a reviewer apply the rule without guessing?"],["Boundary-safe","Are confusable pairs separated by a usable rule?"],["Right granularity","Does the detail match the model objective?"],["Grounded in real data","Has the taxonomy survived actual corpus ambiguity?"]].map(([t,d],i)=><article key={t} className="bg-[#192b43] p-6"><div className="flex items-center justify-between"><CheckCircle2 className="h-5 w-5 text-[#59e8c9]"/><span className="font-mono text-[10px] text-white/40">0{i+1}</span></div><h3 className="mt-5 font-heading font-bold text-white">{t}</h3><p className="mt-2 text-sm leading-6 text-white/65">{d}</p></article>)}</Reveal></div></div></section>;

export const TextProcess = () => <section className="bg-white py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Controlled Learning Loop" title="Our Text Annotation" gradientText="Process" subtitle="Production findings feed back into the taxonomy, guidelines and next calibration cycle."/><Reveal className="relative mx-auto mt-14 max-w-7xl"><svg viewBox="0 0 1200 110" className="absolute left-0 top-6 hidden h-28 w-full lg:block" role="img"><title>Seven-step eQOURSE text annotation process from corpus review and taxonomy stress-test through calibration to delivery</title><defs><marker id="nlp-arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0 0v6l8-3z" fill="#0aa487"/></marker></defs><path d="M60 30 H1135" stroke="#b7d5cf" strokeWidth="2" strokeDasharray="5 7"/><path d="M1135 36 C1135 98 1050 96 1000 96 H310 C205 96 160 75 160 48" fill="none" stroke="#df921a" strokeWidth="2" strokeDasharray="6 6" markerEnd="url(#nlp-arrow)"/></svg><ol className="relative grid gap-4 sm:grid-cols-2 lg:grid-cols-7">{process.map(([n,t,d],i)=><li key={n} className="rounded-2xl border border-[#dce7e4] bg-[#f8faf9] p-5"><span className={`grid h-12 w-12 place-items-center rounded-xl font-mono text-sm font-bold text-white shadow-lg ${i===1?"bg-[#df921a]":"bg-gradient-to-br from-[#087e68] to-[#1ab99b]"}`}>{n}</span><h3 className="mt-6 font-heading font-bold leading-5 text-[#142238]">{t}</h3><p className="mt-3 text-xs leading-5 text-[#657181]">{d}</p></li>)}</ol></Reveal></div></section>;

export const TextQuality = () => <section className="bg-[#edf6f3] py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_1fr] lg:items-center"><Reveal><SectionHeader label="Agreement Is Evidence" title="Quality You Can" gradientText="Measure" centered={false}/><p className="-mt-8 leading-7 text-muted-foreground">We report agreement with the metric that fits the task, expose boundary disagreements separately and adjudicate the cases that teach the taxonomy something new.</p><div className="mt-8 grid grid-cols-2 gap-3">{[["κ / α","Categorical agreement"],["Strict + relaxed F1","Span matching"],["Blind duplicates","Drift detection"],["Gold sets","Expert reference"],["Class distribution","Coverage checks"],["Adjudication","Edge-case resolution"]].map(([v,l])=><div key={l} className="rounded-xl border border-[#d5e5df] bg-white p-4"><strong className="font-heading text-lg text-[#087e68]">{v}</strong><span className="mt-1 block text-xs text-[#506173]">{l}</span></div>)}</div></Reveal><Reveal className="relative"><picture><source srcSet="/assets/ai-data/annotation-labeling/text-nlp-annotation/text-annotation-agreement-calibration.avif" type="image/avif"/><img src="/assets/ai-data/annotation-labeling/text-nlp-annotation/text-annotation-agreement-calibration.webp" alt="Reviewer comparing two annotators' entity spans on the same sentence during an agreement review" width="1000" height="600" loading="lazy" decoding="async" className="w-full rounded-[2rem] border border-white object-cover shadow-[0_24px_70px_rgba(20,34,56,.16)]"/></picture><div className="absolute -bottom-5 left-5 flex items-center gap-3 rounded-xl border border-white/70 bg-white/90 p-4 shadow-xl backdrop-blur"><BadgeCheck className="h-8 w-8 text-primary"/><div><strong className="block text-sm">Boundary disagreement found</strong><span className="text-xs text-muted-foreground">Rule clarified before scale</span></div></div></Reveal></div></div></section>;

export const HardCasesAndLanguages = () => <>
  <section className="bg-[linear-gradient(135deg,#17243a,#252044)] py-20 text-white md:py-24"><div className="container mx-auto px-4"><SectionHeader dark label="Boundary Protocol" title="Where Does the Entity" gradientText="Actually End?" subtitle="Ambiguity is designed into the guidelines before it becomes disagreement in production."/><div className="mx-auto mt-12 grid max-w-7xl gap-px overflow-hidden rounded-[2rem] border border-white/15 bg-white/15 sm:grid-cols-2 lg:grid-cols-4">{hardCases.map(([t,d],i)=><article key={t} className="bg-[#1b2940] p-6 transition hover:bg-[#21334d]"><div className="flex justify-between"><span className="font-mono text-[10px] text-[#59e8c9]">{String(i+1).padStart(2,"0")}</span><span className="h-2 w-2 rounded-full bg-[#f1ad35]"/></div><h3 className="mt-6 font-heading text-lg font-bold text-white">{t}</h3><p className="mt-3 text-sm leading-6 text-white/72">{d}</p></article>)}</div></div></section>
  <section className="overflow-hidden bg-[#fffaf1] py-20 md:py-28"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><Reveal><span className="font-mono text-xs font-bold uppercase tracking-[.18em] text-[#9a6410]">Indic + code-mixed depth</span><h2 className="mt-5 font-heading text-4xl font-bold leading-tight text-[#142238] md:text-5xl">Real language does not stay inside <span className="text-[#087e68]">one script.</span></h2><p className="mt-6 leading-7 text-[#5b6675]">We annotate Hinglish, Tanglish, Manglish, romanised Indic, transliteration variance, mid-sentence script switching, regional dialect and honorific register. A shared core taxonomy is paired with language-specific annexes.</p><div className="mt-7 flex flex-wrap gap-2">{languages.map(x=><span key={x} className="rounded-full border border-[#dbcda9] bg-white px-3 py-2 text-xs font-semibold text-[#5a4a2d]">{x}</span>)}<span className="rounded-full bg-[#142238] px-3 py-2 text-xs font-semibold text-white">+18 languages</span></div></Reveal><Reveal className="relative rounded-[2rem] border border-[#e8dcbf] bg-white p-8 shadow-[0_20px_60px_rgba(93,70,30,.10)]"><div className="space-y-4">{[["Hinglish","Kal meeting reschedule kar do","Romanised Hindi + English"],["தமிழ் + English","Delivery update இன்னும் வரல","Script switching"],["বাংলা + English","Paymentটা pending দেখাচ্ছে","Inflection + borrowed term"],["Register","आप / तुम / you","Honorific and audience context"]].map(([tag,sample,note])=><div key={tag} className="grid gap-3 rounded-xl border border-[#ece5d4] bg-[#fffdf8] p-4 sm:grid-cols-[100px_1fr_auto] sm:items-center"><span className="text-[10px] font-bold uppercase tracking-wider text-[#9a6410]">{tag}</span><span className="font-medium text-[#203047]">{sample}</span><span className="text-xs text-[#687383]">{note}</span></div>)}</div><div className="mt-5 flex items-center gap-3 rounded-xl bg-[#e8f7f3] p-4 text-sm text-[#075f51]"><Languages className="h-5 w-5"/>Native reviewers preserve meaning, register and locale.</div></Reveal></div></div></section>
</>;

export const OperationsAndRelated = () => <>
  <section className="bg-white py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Production Ready" title="Expertise, Formats and" gradientText="Secure Delivery"/><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-3"><Reveal className="rounded-[2rem] border border-border p-7"><Users className="h-7 w-7 text-primary"/><h3 className="mt-5 font-heading text-xl font-bold">Domain-qualified reviewers</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Medical, legal, finance, education, technical and linguistics work is routed to reviewers who understand the subject.</p><Link to="/smes" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary">Meet our Subject Matter Experts <ArrowRight className="h-4 w-4"/></Link></Reveal><Reveal className="rounded-[2rem] bg-[#142238] p-7 text-white"><FileJson2 className="h-7 w-7 text-[#59e8c9]"/><h3 className="mt-5 font-heading text-xl font-bold">Model-ready formats</h3><div className="mt-5 flex flex-wrap gap-2">{["JSON / JSONL","CoNLL-U","BIO / IOBES","spaCy","Hugging Face","brat","XML","CSV / TSV","Label Studio","Custom schema"].map(x=><span key={x} className="rounded-full border border-white/15 bg-white/5 px-3 py-2 text-xs text-white/76">{x}</span>)}</div></Reveal><Reveal className="rounded-[2rem] border border-border p-7"><ShieldCheck className="h-7 w-7 text-primary"/><h3 className="mt-5 font-heading text-xl font-bold">Security by design</h3><ul className="mt-5 space-y-3 text-sm text-muted-foreground">{["ISO-certified processes","NDAs and role-based access","PII redaction or pseudonymisation","Audit trails and defined deletion","Client-controlled environments"].map(x=><li key={x} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{x}</li>)}</ul></Reveal></div><div className="mx-auto mt-12 grid max-w-7xl gap-8 lg:grid-cols-2"><Reveal><h2 className="font-heading text-3xl font-bold">Model-assisted, human-controlled</h2><p className="mt-4 leading-7 text-muted-foreground">Where a usable model or gazetteer exists, reviewers can correct pre-annotations. Recall is monitored against manually annotated controls because missed entities are harder to notice than wrong ones. Early taxonomies, rare classes and highly subjective tasks remain human-first.</p></Reveal><Reveal><h2 className="font-heading text-3xl font-bold">What determines cost?</h2><div className="mt-5 grid grid-cols-2 gap-x-6 gap-y-3">{["Task complexity","Label density","Taxonomy clarity","Text length","Language and domain","Agreement target","Input quality","Security and turnaround"].map((x,i)=><div key={x} className="border-b border-border pb-3 text-sm"><span className="mr-3 font-mono text-[10px] text-primary">{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div></Reveal></div></div></section>
  <section className="bg-[#eef5f3] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Connected Language Data Practice" title="Related Services and" gradientText="Proof"/><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[1.2fr_.8fr]"><Reveal className="grid gap-3 sm:grid-cols-2">{related.map(([title,href,text])=><Link key={title} to={href} className="group rounded-2xl border border-[#d6e4df] bg-white p-5"><div className="flex items-center justify-between"><h3 className="font-heading font-bold text-[#142238]">{title}</h3><ArrowRight className="h-4 w-4 text-primary transition group-hover:translate-x-1"/></div><p className="mt-2 text-xs leading-5 text-[#657181]">{text}</p></Link>)}</Reveal><Reveal className="rounded-[2rem] bg-[#142238] p-8 text-white"><LockKeyhole className="h-7 w-7 text-[#59e8c9]"/><h2 className="mt-5 font-heading text-2xl font-bold">Why eQOURSE</h2><ul className="mt-6 space-y-4">{["Taxonomy stress-test before scale","Agreement metrics delivered with data","Deep Indic and code-mixed coverage","Native and domain-qualified reviewers","Language services under one practice","ISO-certified quality and security"].map(x=><li key={x} className="flex gap-3 text-sm text-white/76"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#59e8c9]"/>{x}</li>)}</ul><div className="mt-8 grid grid-cols-3 gap-2 border-t border-white/15 pt-6">{[["Samples","/ai-data-samples/nlp-annotation"],["Cases","/casestudy"],["Reviews","/clients-testimonials"]].map(([x,h])=><Link key={x} to={h} className="rounded-lg bg-white/5 p-3 text-center text-xs font-semibold hover:bg-white/10">{x}</Link>)}</div></Reveal></div></div></section>
</>;
