import { Link } from "react-router-dom";
import { Activity, ArrowRight, BadgeCheck, CheckCircle2, Clock3, Ear, FileAudio, FileJson2, Gauge, Headphones, Languages, LockKeyhole, Mic2, Radio, ShieldCheck, Sparkles, TimerReset, Users, Volume2, Waves } from "lucide-react";
import SectionHeader from "../../shared/SectionHeader";
import { useScrollReveal } from "@/hooks/use-scroll-reveal";

const Reveal = ({children,className=""}:{children:React.ReactNode;className?:string}) => { const {ref,isVisible}=useScrollReveal(); return <div ref={ref} className={`min-w-0 reveal-up ${isVisible?"visible":""} ${className}`}>{children}</div>; };

const types = [
  [Mic2,"Verbatim Transcription","Every word, filler, false start, repetition and stutter preserved.","ASR training · conversational AI"],
  [FileAudio,"Clean & Normalised Transcription","Disfluencies removed and numbers, dates and tags normalised to a style guide.","Search · subtitles · archives"],
  [Clock3,"Timestamping & Segmentation","Utterance-, sentence- or word-level boundaries with speech and non-speech regions.","Alignment · indexing · datasets"],
  [Activity,"Forced Alignment","Existing transcripts aligned to audio at word or phoneme level.","TTS · pronunciation · research"],
  [Users,"Speaker Diarization","Who spoke when, including consistent identities through interruption and overlap.","Calls · meetings · broadcast"],
  [Ear,"Speaker ID & Voice Matching","Known speakers or roles matched within and across recordings.","Role-aware analytics · biometrics"],
  [Languages,"Language & Dialect ID","Language, regional dialect and accent tagged at segment level, including switches.","Routing · accent robustness"],
  [Waves,"Emotion & Tone","Frustration, urgency, hesitation, stress and satisfaction inferred from delivery.","Voice assistants · call QA"],
  [Radio,"Acoustic Events","Alarms, machinery, footsteps, vehicles and environmental sounds time-coded.","Industry · security · smart home"],
  [Volume2,"Phonetic Transcription","Actual pronunciation represented with IPA or a custom phone set.","TTS · accents · low-resource speech"],
  [Sparkles,"Wake Word & Keywords","Targets, near-misses and deliberate negatives precisely time-boxed.","Assistants · commands · compliance"],
  [Gauge,"Audio Quality & TTS QC","Signal, intelligibility, clipping, pronunciation, pacing and prosody reviewed.","Curation · synthetic voice QA"],
] as const;

const process = [
  ["01","Audio assessment","Measure quality, speaker count, overlap, accent and background conditions."],
  ["02","Style guide","Fix transcription style, tags, speakers, timing and every known edge case."],
  ["03","Listener matching","Qualify native listeners by language, accent and domain."],
  ["04","Calibration","Several reviewers label the same clips; disagreements refine the guide."],
  ["05","Pilot","Confirm WER, DER, throughput and acceptance thresholds."],
  ["06","Production + QA","Monitor error rates and listener performance continuously."],
  ["07","Delivery + iteration","Ship data and feed new cases back into the style guide."],
] as const;

const hardCases = [
  ["Overlapping speech","Transcribe both voices or only the dominant speaker? The rule is explicit."],
  ["Inaudible segments","Flagged with duration and never plausibly invented."],
  ["Far-field + noise","Achievable accuracy is scoped by condition, not hidden in an average."],
  ["Telephony artefacts","8 kHz audio removes cues that distinguish similar consonants."],
  ["Names + proper nouns","Project glossaries and uncertainty flags replace approximation."],
  ["Domain vocabulary","Clinical, legal and technical terms go to matched listeners."],
  ["Speaker-count drift","Late joiners receive new identities; labels are never casually reused."],
  ["Silence + music","Inclusion, exclusion and event tagging are decided before scale."],
] as const;

const languages=["English","Spanish","French","German","Portuguese","Arabic","Mandarin","Japanese","Hindi","Bengali","Tamil","Telugu","Marathi","Gujarati","Kannada","Malayalam","Punjabi","Odia","Assamese","Urdu"];

const Waveform = ({seed=0,color="#0aa487"}:{seed?:number;color?:string}) => <div className="flex h-16 items-center gap-[3px] overflow-hidden" aria-hidden="true">{Array.from({length:54},(_,i)=>{const h=10+Math.abs(Math.sin((i+seed)*1.37))*42;return <span key={i} className="w-1 shrink-0 rounded-full motion-safe:animate-pulse" style={{height:h,backgroundColor:color,opacity:.32+((i%5)/8),animationDelay:`${i*35}ms`}}/>})}</div>;

const AudioTypesVisual = () => <div className="overflow-hidden rounded-[2rem] border border-[#d7e2e0] bg-white shadow-[0_24px_70px_rgba(17,31,50,.10)]"><div className="flex items-center justify-between border-b border-[#e2e9e7] px-6 py-4"><span className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[#087e68]">Speech-layer annotation canvas</span><span className="font-mono text-[10px] text-[#8a97a2]">00:24:18</span></div><div className="grid md:grid-cols-2">
  <article className="border-b border-r border-[#e2e9e7] p-6"><span className="text-[10px] font-bold uppercase tracking-wider text-[#697783]">Speaker diarization + overlap</span><Waveform/><div className="relative mt-2 flex h-9 gap-1"><span className="w-[28%] rounded bg-[#0aa487]/80"/><span className="w-[22%] rounded bg-[#508fce]/75"/><span className="w-[18%] rounded bg-[#0aa487]/80"/><span className="w-[32%] rounded bg-[#9b77ce]/75"/><span className="absolute left-[42%] top-2 h-5 w-[13%] rounded border border-amber-500 bg-amber-300/75"/></div><div className="mt-2 flex justify-between text-[9px] font-bold uppercase text-[#697783]"><span>Speaker A</span><span className="text-amber-700">Overlap</span><span>Speaker C</span></div></article>
  <article className="border-b border-[#e2e9e7] p-6"><span className="text-[10px] font-bold uppercase tracking-wider text-[#697783]">Word-level timing</span><Waveform seed={8} color="#4b8fd0"/><div className="mt-2 grid grid-cols-7 gap-1">{[15,24,18,30,12,27,20].map((w,i)=><div key={i} className="border-l border-[#4b8fd0] pl-1"><div className="h-2 rounded bg-[#dbe7f1]" style={{width:`${w+40}%`}}/></div>)}</div><div className="mt-4 h-px bg-[repeating-linear-gradient(90deg,#9db0bd_0_1px,transparent_1px_18px)]"/></article>
  <article className="border-r border-[#e2e9e7] p-6"><span className="text-[10px] font-bold uppercase tracking-wider text-[#697783]">Acoustic events</span><Waveform seed={14} color="#667482"/><div className="relative mt-1 h-10 border-t border-[#d9e2df]">{[[12,"door"],[47,"alarm"],[78,"engine"]].map(([x,t],i)=><span key={String(t)} className={`absolute top-2 rounded px-2 py-1 text-[9px] font-bold ${i===1?"bg-amber-100 text-amber-800":"bg-[#e1f5f0] text-[#087e68]"}`} style={{left:`${x}%`}}>{t}</span>)}</div></article>
  <article className="p-6"><span className="text-[10px] font-bold uppercase tracking-wider text-[#697783]">Emotion over time</span><Waveform seed={21} color="#9870c5"/><div className="mt-2 h-4 overflow-hidden rounded-full bg-gradient-to-r from-[#0aa487] via-[#e6a130] to-[#9b77ce]"/><div className="mt-3 flex justify-between text-[9px] uppercase text-[#697783]"><span>calm</span><span>urgent</span><span>uncertain</span></div></article>
</div></div>;

export const AudioDefinition = () => <section className="bg-white py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><Reveal><SectionHeader label="Sound Into Structure" title="What Is Audio & Speech" gradientText="Annotation?" centered={false}/><div className="-mt-8 space-y-4 leading-7 text-muted-foreground"><p>Audio annotation turns recorded sound into machine-readable data: what was said, who said it, when they said it, how they said it and what else was audible.</p><p>Real audio is two callers speaking over each other, a voice command across a room or a doctor dictating over ward noise. The annotation must represent that mess honestly rather than silently cleaning it away.</p><p><Link to="/ai-data-services/model-testing/asr-speech-model-testing" className="font-semibold text-primary hover:underline">ASR &amp; speech model testing</Link> is the separate downstream deliverable: it produces error rates and failure analysis used to decide whether a model is fit to ship, while annotation produces transcripts and labelled audio used to train or fine-tune it.</p></div><div className="mt-8 grid gap-3 sm:grid-cols-2"><Link to="/ai-data-services/data-collection/audio-data-collection" className="rounded-xl border border-border p-4 text-sm hover:border-primary/40"><strong className="block">Need recordings first?</strong><span className="mt-1 block text-muted-foreground">Audio Data Collection Services</span></Link><Link to="/ai-data-services/annotation-labeling/text-nlp-annotation" className="rounded-xl border border-border p-4 text-sm hover:border-primary/40"><strong className="block">Need meaning after transcription?</strong><span className="mt-1 block text-muted-foreground">Text &amp; NLP Annotation Services</span></Link></div></Reveal><Reveal><AudioTypesVisual/></Reveal></div></div></section>;

export const AudioAnnotationTypes = () => <section className="bg-[#f4f8f7] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Speech Layers" title="Audio & Speech Annotation Types" gradientText="We Deliver" subtitle="Every layer answers a different engineering question: words, speakers, time, delivery or surrounding sound."/><Reveal className="mx-auto mt-12 max-w-6xl"><AudioTypesVisual/></Reveal><div className="mx-auto mt-10 grid max-w-7xl gap-3 md:grid-cols-2 xl:grid-cols-4">{types.map(([Icon,title,text,best],i)=><article key={title} className="rounded-2xl border border-[#d6e3df] bg-white p-5 transition hover:-translate-y-1 hover:border-primary/35"><div className="flex justify-between"><Icon className="h-5 w-5 text-primary"/><span className="font-mono text-[10px] text-[#087e68]">{String(i+1).padStart(2,"0")}</span></div><h3 className="mt-5 font-heading font-bold text-[#142238]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#5f6c79]">{text}</p><p className="mt-4 border-t border-[#e2e9e7] pt-3 text-[10px] font-bold uppercase tracking-wider text-[#087e68]">Best for: {best}</p>{title==="Audio Quality & TTS QC"&&<Link to="/voice-over-services" className="mt-3 inline-block text-xs font-semibold text-primary hover:underline">Voice-Over Services</Link>}</article>)}</div></div></section>;

const comparisonRows=[["Fillers","Captured","Removed"],["False starts","Captured","Removed"],["Stutters","Marked","Removed"],["Grammar","Preserved","Per specification"],["Numbers + dates","As spoken","Normalised"],["Non-speech","Tagged","Usually omitted"],["Relative cost","Higher","Lower"],["Right for","ASR + conversation","Subtitles + search"]];
export const VerbatimDecision = () => <section className="relative overflow-hidden bg-[#142238] py-20 text-white md:py-28"><div className="absolute inset-0 opacity-[.05]" style={{backgroundImage:"linear-gradient(90deg,#58e4c8 1px,transparent 1px)",backgroundSize:"32px 100%"}}/><div className="container relative mx-auto px-4"><SectionHeader dark label="The First Specification Decision" title="Verbatim vs. Clean Transcription—" gradientText="Choose Before You Start" subtitle="This decision changes cost, model behaviour and whether the output can be transformed later."/><div className="mx-auto mt-12 grid max-w-7xl gap-10 lg:grid-cols-[1.1fr_.9fr]"><Reveal className="overflow-hidden rounded-[2rem] border border-white/15"><div className="grid grid-cols-[1.2fr_1fr_1fr] bg-white/10 text-xs font-bold uppercase tracking-wider"><span className="p-4">Decision</span><span className="border-l border-white/10 p-4 text-[#59e8c9]">Verbatim</span><span className="border-l border-white/10 p-4 text-[#f4bd56]">Clean</span></div>{comparisonRows.map(([a,b,c])=><div key={a} className="grid grid-cols-[1.2fr_1fr_1fr] border-t border-white/10 text-sm"><strong className="p-4 text-white/85">{a}</strong><span className="border-l border-white/10 p-4 text-white/68">{b}</span><span className="border-l border-white/10 p-4 text-white/68">{c}</span></div>)}</Reveal><Reveal><div className="rounded-[2rem] bg-[#1b3049] p-8"><Headphones className="h-8 w-8 text-[#59e8c9]"/><h3 className="mt-6 font-heading text-2xl font-bold">Why it changes what the model learns</h3><p className="mt-4 leading-7 text-white/72">Train ASR on tidy transcripts and it never learns the shape of real speech: interruptions, fillers, partial words and repetition. But verbatim output is expensive noise when the end product is readable subtitles or search.</p><p className="mt-5 rounded-xl border border-[#59e8c9]/25 bg-[#59e8c9]/8 p-5 text-sm leading-6 text-white/82"><strong className="text-[#59e8c9]">Our usual ASR recommendation:</strong> verbatim with structured tags. Tagged speech can be cleaned later; cleaned speech cannot be reconstructed.</p><h3 className="mt-7 font-heading font-bold">Decisions inside the decision</h3><p className="mt-3 text-sm leading-6 text-white/62">Numbers, dates, currencies, acronyms, profanity, inaudibility, overlap, dialect grammar and unfamiliar names all receive written rules in the pilot style guide.</p></div></Reveal></div></div></section>;

export const AudioProcess = () => <section className="bg-white py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Versioned Listening Loop" title="Our Audio Annotation" gradientText="Process" subtitle="New acoustic conditions feed back into the style guide—not into undocumented reviewer intuition."/><Reveal className="relative mx-auto mt-14 max-w-7xl"><svg viewBox="0 0 1200 110" className="absolute left-0 top-6 hidden h-28 w-full lg:block" role="img"><title>Seven-step eQOURSE audio annotation process from audio assessment and style guide through calibration to delivery</title><defs><marker id="aud-arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0 0v6l8-3z" fill="#0aa487"/></marker></defs><path d="M60 30 H1135" stroke="#b7d5cf" strokeWidth="2" strokeDasharray="5 7"/><path d="M1135 36 C1135 98 1050 96 1000 96 H310 C205 96 160 75 160 48" fill="none" stroke="#d99a28" strokeWidth="2" strokeDasharray="6 6" markerEnd="url(#aud-arrow)"/></svg><ol className="relative grid gap-4 sm:grid-cols-2 lg:grid-cols-7">{process.map(([n,t,d],i)=><li key={n} className="rounded-2xl border border-[#dce7e4] bg-[#f8faf9] p-5"><span className={`grid h-12 w-12 place-items-center rounded-xl font-mono text-sm font-bold text-white shadow-lg ${i===1?"bg-[#d99a28]":"bg-gradient-to-br from-[#087e68] to-[#1ab99b]"}`}>{n}</span><h3 className="mt-6 font-heading font-bold leading-5 text-[#142238]">{t}</h3><p className="mt-3 text-xs leading-5 text-[#657181]">{d}</p></li>)}</ol></Reveal></div></section>;

export const SpeechQuality = () => <section className="bg-[#edf6f3] py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><Reveal><SectionHeader label="Listen, Measure, Separate" title="How We Measure Speech" gradientText="Annotation Quality" centered={false}/><p className="-mt-8 leading-7 text-muted-foreground">Transcription and speaker attribution are scored separately. Error is also broken down by clean, noisy, overlapping and accented speech so a comfortable average cannot conceal a weak condition.</p><div className="mt-8 grid grid-cols-2 gap-3">{[["WER + CER","Words and script-aware characters"],["Raw + normalised","True recognition vs formatting"],["DER","Speaker attribution"],["Boundary offset","Timestamp accuracy"],["Gold clips","Hidden drift detection"],["Listening review","Catches plausible ASR errors"]].map(([v,l])=><div key={v} className="rounded-xl border border-[#d4e5df] bg-white p-4"><strong className="font-heading text-lg text-[#087e68]">{v}</strong><span className="mt-1 block text-xs text-[#596879]">{l}</span></div>)}</div></Reveal><Reveal className="relative"><picture><source srcSet="/assets/ai-data/annotation-labeling/audio-speech-annotation/audio-annotation-wer-quality-review.avif" type="image/avif"/><img src="/assets/ai-data/annotation-labeling/audio-speech-annotation/audio-annotation-wer-quality-review.webp" alt="Reviewer comparing a transcript against expert reference with word error rate and diarization metrics displayed" width="1000" height="600" loading="lazy" decoding="async" className="w-full rounded-[2rem] border border-white object-cover shadow-[0_24px_70px_rgba(17,31,50,.16)]"/></picture><div className="absolute -bottom-5 left-5 flex items-center gap-3 rounded-xl border border-white/70 bg-white/90 p-4 shadow-xl backdrop-blur"><BadgeCheck className="h-8 w-8 text-primary"/><div><strong className="block text-sm">Second-pass listening</strong><span className="text-xs text-muted-foreground">Not a silent transcript review</span></div></div></Reveal></div></div></section>;

export const HardSpeechAndIndia = () => <>
  <section className="bg-[linear-gradient(135deg,#17243a,#242040)] py-20 text-white md:py-24"><div className="container mx-auto px-4"><SectionHeader dark label="Acoustic Edge Cases" title="The Hard Parts of" gradientText="Real-World Speech" subtitle="Every difficult condition receives a written, versioned ruling before production."/><div className="mx-auto mt-12 grid max-w-7xl gap-px overflow-hidden rounded-[2rem] border border-white/15 bg-white/15 sm:grid-cols-2 lg:grid-cols-4">{hardCases.map(([t,d],i)=><article key={t} className="bg-[#1b2940] p-6 transition hover:bg-[#21344e]"><div className="flex justify-between"><span className="font-mono text-[10px] text-[#59e8c9]">{String(i+1).padStart(2,"0")}</span><span className="h-2 w-2 rounded-full bg-[#f1ad35]"/></div><h3 className="mt-6 font-heading text-lg font-bold text-white">{t}</h3><p className="mt-3 text-sm leading-6 text-white/72">{d}</p></article>)}</div></div></section>
  <section className="overflow-hidden bg-[#fffaf1] py-20 md:py-28"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><Reveal><span className="font-mono text-xs font-bold uppercase tracking-[.18em] text-[#98610c]">Global reach, India-wide depth</span><h2 className="mt-5 font-heading text-4xl font-bold leading-tight text-[#142238] md:text-5xl">Global language coverage with <span className="text-[#087e68]">India's regional depth.</span></h2><p className="mt-6 leading-7 text-[#5d6875]">We deliver speech annotation across 30+ global languages for international voice AI programmes. Our specialist strength is comprehensive coverage across India's regional languages, accents and dialects—including conversations that switch language, script, register and vocabulary mid-sentence.</p><div className="mt-7 flex flex-wrap gap-2">{languages.map(x=><span key={x} className="rounded-full border border-[#ddcfaa] bg-white px-3 py-2 text-xs font-semibold text-[#5a492a]">{x}</span>)}<span className="rounded-full bg-[#142238] px-3 py-2 text-xs font-semibold text-white">More Indian + global languages</span></div></Reveal><Reveal className="rounded-[2rem] border border-[#e7dcbc] bg-white p-7 shadow-[0_20px_60px_rgba(93,70,30,.10)]"><div className="space-y-4">{[["Global programmes","Native-listener delivery across European, Asian and Middle Eastern languages"],["India-wide coverage","Regional languages and local speech patterns across Indian markets"],["Indian English","Regional pronunciation and first-language influence"],["Code-switched speech","Hinglish, Tanglish, Manglish and other mixed-language patterns"],["Dialect + register","Rural, urban, formal and lower-resource speech varieties"]].map(([t,d],i)=><div key={t} className="grid grid-cols-[44px_1fr] gap-4 border-b border-[#ece4d2] pb-4 last:border-0"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#e6f6f2] font-mono text-[10px] font-bold text-[#087e68]">0{i+1}</span><div><h3 className="font-heading font-bold text-[#142238]">{t}</h3><p className="mt-1 text-sm leading-6 text-[#687383]">{d}</p></div></div>)}</div></Reveal></div></div></section>
</>;

export const DeliveryUseCases = () => <section className="bg-white py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Model-Ready Handoff" title="Formats, Audio Handling and" gradientText="Use Cases"/><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[.8fr_1.2fr]"><Reveal className="rounded-[2rem] bg-[#142238] p-8 text-white"><FileJson2 className="h-7 w-7 text-[#59e8c9]"/><h3 className="mt-5 font-heading text-2xl font-bold">Output formats</h3><div className="mt-5 flex flex-wrap gap-2">{["JSON / JSONL","RTTM","CTM","TextGrid","SRT / VTT","Kaldi","Hugging Face","ELAN EAF","CSV / TSV","Speaker text","Custom schema"].map(x=><span key={x} className="rounded-full border border-white/15 bg-white/5 px-3 py-2 text-xs text-white/76">{x}</span>)}</div><p className="mt-7 border-t border-white/15 pt-5 text-sm leading-6 text-white/65">WAV, MP3, FLAC, OGG, M4A and telephony formats · mono or multi-channel · manifest, WER/DER report, speaker inventory and versioned style guide.</p></Reveal><Reveal className="grid gap-px overflow-hidden rounded-[2rem] border border-border bg-border sm:grid-cols-2">{[["ASR & voice AI","Verbatim, timing, accent and dialect"],["Call analytics","Diarization, roles, emotion and keywords"],["TTS & voice cloning","Alignment, phonetics and prosody"],["Healthcare","Clinical dictation with domain vocabulary"],["Security + industry","Acoustic events and anomaly sounds"],["Accessibility + media","Caption-ready transcripts and timing"]].map(([t,d])=><article key={t} className="bg-card p-6"><h3 className="font-heading font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{d}</p></article>)}</Reveal></div><div className="mx-auto mt-7 flex max-w-7xl flex-wrap gap-3"><Link to="/subtitling-services" className="rounded-full border border-border px-4 py-2 text-sm font-semibold hover:border-primary hover:text-primary">Subtitling Services</Link><Link to="/accessible-media-enhancements" className="rounded-full border border-border px-4 py-2 text-sm font-semibold hover:border-primary hover:text-primary">Accessible Media Enhancements</Link></div></div></section>;

export const ASRSecurityAndCost = () => <>
  <section className="bg-[#f4f8f7] py-20 md:py-24"><div className="container mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><Reveal><SectionHeader label="Human-Controlled Acceleration" title="ASR Assistance—Where It Helps and" gradientText="Where It Hurts" centered={false}/><div className="-mt-8 space-y-4 leading-7 text-muted-foreground"><p>Clean, single-speaker, standard-accent audio can be corrected from machine transcription faster than it can be typed from scratch.</p><p>The risk is a fluent, plausible error: a name becomes a common word and the sentence still reads perfectly. Every assisted batch therefore receives a listening review.</p><p className="font-semibold text-foreground">Accented, overlapping, noisy, code-switched and specialist audio returns to manual transcription when ASR stops helping.</p></div></Reveal><Reveal className="rounded-[2rem] border border-[#d6e4df] bg-white p-8"><LockKeyhole className="h-7 w-7 text-primary"/><h2 className="mt-5 font-heading text-2xl font-bold">Voice is biometric data</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Controls are agreed at scoping: the data controller retains responsibility for consent and lawful basis.</p><ul className="mt-6 grid gap-3 text-sm text-foreground/75">{["ISO 9001 and ISO 27001 processes","Named, vetted pools under NDA","Role-based access and audit trails","Transcript PII redaction and audio masking","Restricted or client-controlled environments","Contract-defined retention and deletion"].map(x=><li key={x} className="flex gap-3"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{x}</li>)}</ul><Link to="/ai-data-services/data-collection/audio-data-collection" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-primary">Audio collection with consent and provenance <ArrowRight className="h-4 w-4"/></Link></Reveal></div></div></section>
  <section className="relative overflow-hidden bg-[#102237] py-20 text-white md:py-28"><div className="absolute inset-x-0 top-1/2 h-px bg-white/10"/><div className="container relative mx-auto px-4"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><Reveal><span className="font-mono text-xs font-bold uppercase tracking-[.18em] text-[#59e8c9]">The number behind the quote</span><h2 className="mt-5 font-heading text-4xl font-bold leading-tight md:text-5xl">Start with the <span className="text-[#59e8c9]">real-time ratio.</span></h2><p className="mt-6 leading-7 text-white/70">Speech is priced per audio hour, but complexity determines how many working hours sit behind it. These planning ranges must be confirmed against your pilot audio.</p></Reveal><Reveal className="grid gap-3 sm:grid-cols-3">{[["2–4×","Clean","Single speaker · clean transcript"],["4–8×","Structured","Verbatim · speakers · timestamps"],[">10×","Difficult","Overlap · accents · noise · word timing"]].map(([v,t,d],i)=><article key={t} className={`rounded-2xl border p-6 ${i===1?"border-[#59e8c9]/45 bg-[#59e8c9]/10":"border-white/15 bg-white/[.05]"}`}><strong className={`font-heading text-4xl ${i===1?"text-[#59e8c9]":"text-white"}`}>{v}</strong><h3 className="mt-5 font-heading font-bold">{t}</h3><p className="mt-2 text-xs leading-5 text-white/60">{d}</p></article>)}</Reveal></div><div className="mx-auto mt-12 grid max-w-7xl gap-x-8 sm:grid-cols-2 lg:grid-cols-5">{["Transcription style","Timing granularity","Speakers + overlap","Audio quality","Accent + language","Code-switching","Domain vocabulary","Extra label layers","Accuracy tier","Security + turnaround"].map((x,i)=><div key={x} className="border-b border-white/12 py-4 text-sm text-white/72"><span className="mr-3 font-mono text-[10px] text-[#59e8c9]">{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div></div></section>
</>;

const related=[["ASR & Speech Model Testing","/ai-data-services/model-testing/asr-speech-model-testing"],["Audio Data Collection","/ai-data-services/data-collection/audio-data-collection"],["Text & NLP Annotation","/ai-data-services/annotation-labeling/text-nlp-annotation"],["Video Annotation","/ai-data-services/annotation-labeling/video-annotation"],["Subtitling Services","/subtitling-services"],["Voice-Over Services","/voice-over-services"],["Translation Services","/translation-services"],["Accessible Media","/accessible-media-enhancements"],["Data Cleaning & Validation","/ai-data-services/cleaning-validation"],["All Annotation Services","/ai-data-services/annotation-labeling"]] as const;
export const AudioRelated = () => <section className="bg-[#edf5f2] py-20 md:py-24"><div className="container mx-auto px-4"><SectionHeader label="Connected Speech Practice" title="Related Services and" gradientText="Proof"/><div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[1.15fr_.85fr]"><Reveal className="grid gap-3 sm:grid-cols-2">{related.map(([t,h])=><Link key={t} to={h} className="group flex items-center justify-between rounded-2xl border border-[#d6e4df] bg-white p-5"><h3 className="font-heading font-bold text-[#142238]">{t}</h3><ArrowRight className="h-4 w-4 text-primary transition group-hover:translate-x-1"/></Link>)}</Reveal><Reveal className="rounded-[2rem] bg-[#142238] p-8 text-white"><Headphones className="h-7 w-7 text-[#59e8c9]"/><h2 className="mt-5 font-heading text-2xl font-bold">Why eQOURSE for speech annotation</h2><ul className="mt-6 space-y-4">{["Native-listener delivery across 30+ global languages","Comprehensive Indian regional-language coverage","Indian accents, dialects and mixed speech","WER reported by audio condition","Diarization scored independently","Second-pass listening review","ISO-certified processes"].map(x=><li key={x} className="flex gap-3 text-sm text-white/76"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#59e8c9]"/>{x}</li>)}</ul><div className="mt-8 grid grid-cols-3 gap-2 border-t border-white/15 pt-6">{[["Samples","/ai-data-samples/audio-speech"],["Cases","/casestudy"],["Reviews","/clients-testimonials"]].map(([x,h])=><Link key={x} to={h} className="rounded-lg bg-white/5 p-3 text-center text-xs font-semibold hover:bg-white/10">{x}</Link>)}</div></Reveal></div></div></section>;
